/**
 * Audit Repository
 *
 * Provides functions for recording and querying audit trail records.
 * Audits track CREATE/UPDATE/DELETE operations with field-level changes.
 * 
 * Note: Audit IDs are auto-generated by InstantDB (not deterministic)
 * since audits are append-only and don't need idempotent upserts.
 */

import { id } from "@instantdb/admin";
import { db } from "../client";
import type { Audit, FieldChange } from "@financial-graph/shared";
import { isEntityAudited } from "./audit-config";

const AUDIT_RETENTION_DAYS = parseInt(process.env.AUDIT_RETENTION_DAYS || "7");

/**
 * Record an audit event for an entity change
 * 
 * Automatically checks if audit trail is enabled for the entity type.
 * If disabled, returns null without recording.
 */
export async function recordAudit(params: {
  entity_type: string;
  entity_id: string;
  operation: "CREATE" | "UPDATE" | "DELETE";
  changed_by: "heuristic" | "llm" | "human";
  fields_changed: FieldChange[];
  source_id?: string;
}): Promise<string | null> {
  // Check if audit trail is enabled for this entity
  if (!isEntityAudited(params.entity_type)) {
    return null;
  }

  const changed_at = new Date().toISOString();
  const expires_at = new Date(
    Date.now() + AUDIT_RETENTION_DAYS * 24 * 60 * 60 * 1000
  ).toISOString();

  const auditId = id();

  const audit: Audit = {
    id: auditId,
    entity_type: params.entity_type,
    entity_id: params.entity_id,
    operation: params.operation,
    changed_by: params.changed_by,
    changed_at,
    source_id: params.source_id,
    fields_changed: params.fields_changed,
    expires_at,
  };

  await db.transact([db.tx.audit[auditId].update(audit)]);

  return auditId;
}

/**
 * Get all audits for a specific entity
 */
export async function getAuditsForEntity(
  entityType: string,
  entityId: string
): Promise<Audit[]> {
  const result = await db.query({
    audit: {
      $: {
        where: {
          entity_type: entityType,
          entity_id: entityId,
        },
        order: { serverCreatedAt: "desc" },
      },
    },
  });

  return (result.audit || []) as Audit[];
}

/**
 * Prune expired audit records (older than AUDIT_RETENTION_DAYS)
 * Returns the count of deleted records
 */
export async function pruneExpiredAudits(): Promise<number> {
  const now = new Date().toISOString();

  const result = await db.query({
    audit: {
      $: {
        where: {
          expires_at: { $lt: now },
        },
        limit: 1000,
      },
    },
  });

  const expired = result.audit || [];
  if (expired.length === 0) return 0;

  const txs = expired.map((auditRecord: any) =>
    db.tx.audit[auditRecord.id].delete()
  );

  await db.transact(txs);
  return expired.length;
}

/**
 * Compute field-level changes between old and new entity states
 * 
 * @param oldState - Previous entity state (or null for CREATE operations)
 * @param newState - New entity state
 * @param trackedFields - Optional array of field names to track (empty = all fields)
 * @returns Array of FieldChange objects
 */
export function computeFieldChanges(
  oldState: Record<string, any> | null,
  newState: Record<string, any>,
  trackedFields: string[] = []
): FieldChange[] {
  const changes: FieldChange[] = [];

  // If no old state, this is a CREATE operation - track all fields
  if (!oldState) {
    const fieldsToTrack = trackedFields.length > 0 
      ? trackedFields 
      : Object.keys(newState).filter(key => key !== 'id' && key !== 'updated_at');
    
    for (const field of fieldsToTrack) {
      if (newState[field] !== undefined) {
        changes.push({
          field,
          old_value: null,
          new_value: serializeValue(newState[field]),
        });
      }
    }
    return changes;
  }

  // For UPDATE operations, compare old and new states
  const fieldsToCheck = trackedFields.length > 0 
    ? trackedFields 
    : Object.keys({ ...oldState, ...newState }).filter(key => key !== 'id' && key !== 'updated_at');

  for (const field of fieldsToCheck) {
    const oldValue = oldState[field];
    const newValue = newState[field];

    // Skip if values are the same
    if (JSON.stringify(oldValue) === JSON.stringify(newValue)) {
      continue;
    }

    changes.push({
      field,
      old_value: serializeValue(oldValue),
      new_value: serializeValue(newValue),
    });
  }

  return changes;
}

/**
 * Serialize a value for storage in audit trail
 * Handles complex types like objects, arrays, dates, etc.
 */
function serializeValue(value: any): any {
  if (value === null || value === undefined) {
    return null;
  }
  
  if (value instanceof Date) {
    return value.toISOString();
  }
  
  if (typeof value === 'object') {
    return JSON.parse(JSON.stringify(value));
  }
  
  return value;
}
