/**
 * Audit Repository
 *
 * Provides functions for recording and querying audit trail records.
 * Audits track CREATE/UPDATE/DELETE operations with field-level changes.
 * 
 * Note: Audit IDs are auto-generated by InstantDB (not deterministic)
 * since audits are append-only and don't need idempotent upserts.
 */

import { id } from "@instantdb/admin";
import { db } from "../client";
import type { Audit, FieldChange } from "@financial-graph/shared";

const AUDIT_RETENTION_DAYS = parseInt(process.env.AUDIT_RETENTION_DAYS || "7");

/**
 * Record an audit event for an entity change
 */
export async function recordAudit(params: {
  entity_type: string;
  entity_id: string;
  operation: "CREATE" | "UPDATE" | "DELETE";
  changed_by: "heuristic" | "llm" | "human";
  fields_changed: FieldChange[];
  source_id?: string;
}): Promise<string> {
  const changed_at = new Date().toISOString();
  const expires_at = new Date(
    Date.now() + AUDIT_RETENTION_DAYS * 24 * 60 * 60 * 1000
  ).toISOString();

  const auditId = id();

  const audit: Audit = {
    id: auditId,
    entity_type: params.entity_type,
    entity_id: params.entity_id,
    operation: params.operation,
    changed_by: params.changed_by,
    changed_at,
    source_id: params.source_id || null,
    fields_changed: params.fields_changed,
    expires_at,
  };

  await db.transact([db.tx.audit[auditId].update(audit)]);

  return auditId;
}

/**
 * Get all audits for a specific entity
 */
export async function getAuditsForEntity(
  entityType: string,
  entityId: string
): Promise<Audit[]> {
  const result = await db.query({
    audit: {
      $: {
        where: {
          entity_type: entityType,
          entity_id: entityId,
        },
        order: { serverCreatedAt: "desc" },
      },
    },
  });

  return (result.audit || []) as Audit[];
}

/**
 * Prune expired audit records (older than AUDIT_RETENTION_DAYS)
 * Returns the count of deleted records
 */
export async function pruneExpiredAudits(): Promise<number> {
  const now = new Date().toISOString();

  const result = await db.query({
    audit: {
      $: {
        where: {
          expires_at: { $lt: now },
        },
        limit: 1000,
      },
    },
  });

  const expired = result.audit || [];
  if (expired.length === 0) return 0;

  const txs = expired.map((auditRecord: any) =>
    db.tx.audit[auditRecord.id].delete()
  );

  await db.transact(txs);
  return expired.length;
}
