export const GICS = {
  INFORMATION_TECHNOLOGY: 45,
  ENERGY: 10,
  CONSUMER_DISCRETIONARY: 25,
  CONSUMER_STAPLES: 30,
  HEALTH_CARE: 35,
  MATERIALS: 15,
  INDUSTRIALS: 20,
  FINANCIALS: 40,
  COMMUNICATION_SERVICES: 50,
  UTILITIES: 55,
  REAL_ESTATE: 60,
} as const;

export type GICS = (typeof GICS)[keyof typeof GICS];
