/**
 * Standard Industrial Classification (SIC) Codes
 * Source: SEC Division of Corporation Finance
 * 
 * Maps SIC code to industry description for display purposes
 */

export const SIC_CODES: Record<string, string> = {
  // Agriculture, Forestry, and Fishing (0100-0999)
  "0100": "Agricultural Production - Crops",
  "0200": "Agricultural Production - Livestock",
  "0700": "Agricultural Services",
  "0800": "Forestry",
  "0900": "Fishing, Hunting and Trapping",

  // Mining (1000-1499)
  "1000": "Metal Mining",
  "1040": "Gold and Silver Ores",
  "1090": "Miscellaneous Metal Ores",
  "1220": "Bituminous Coal and Lignite Mining",
  "1311": "Crude Petroleum and Natural Gas",
  "1381": "Drilling Oil and Gas Wells",
  "1382": "Oil and Gas Field Exploration Services",
  "1389": "Oil and Gas Field Services",
  "1400": "Mining and Quarrying of Nonmetallic Minerals",

  // Construction (1500-1799)
  "1500": "Building Construction - General Contractors",
  "1520": "General Bldg Contractors - Residential Bldgs",
  "1531": "Operative Builders",
  "1540": "General Bldg Contractors - Nonresidential Bldgs",
  "1600": "Heavy Construction Other Than Bldg Const - Contractors",
  "1623": "Water, Sewer, Pipeline, Comm and Power Line Construction",
  "1700": "Construction - Special Trade Contractors",

  // Manufacturing (2000-3999)
  "2000": "Food and Kindred Products",
  "2011": "Meat Packing Plants",
  "2013": "Sausages and Other Prepared Meat Products",
  "2015": "Poultry Slaughtering and Processing",
  "2020": "Dairy Products",
  "2024": "Ice Cream and Frozen Desserts",
  "2030": "Canned, Frozen & Preserved Fruit, Veg & Food Specialties",
  "2033": "Canned, Fruits, Veg, Preserves, Jams & Jellies",
  "2040": "Grain Mill Products",
  "2050": "Bakery Products",
  "2060": "Sugar and Confectionery Products",
  "2070": "Fats and Oils",
  "2080": "Beverages",
  "2082": "Malt Beverages",
  "2086": "Bottled and Canned Soft Drinks and Carbonated Waters",
  "2090": "Miscellaneous Food Preparations and Kindred Products",
  "2100": "Tobacco Products",
  "2111": "Cigarettes",
  "2200": "Textile Mill Products",
  "2300": "Apparel and Other Finished Products Made From Fabrics",
  "2320": "Men's and Boys' Furnishings, Work Clothing, and Allied Garments",
  "2330": "Women's, Misses', and Juniors' Outerwear",
  "2340": "Women's, Misses', Children's & Infants' Undergarments",
  "2390": "Miscellaneous Fabricated Textile Products",
  "2400": "Lumber and Wood Products, Except Furniture",
  "2421": "Sawmills and Planing Mills, General",
  "2430": "Millwood, Veneer, Plywood, and Structural Wood Members",
  "2451": "Mobile Homes",
  "2452": "Prefabricated Wood Buildings and Components",
  "2510": "Household Furniture",
  "2511": "Wood Household Furniture, (No Upholstered)",
  "2520": "Office Furniture",
  "2522": "Office Furniture (No Wood)",
  "2531": "Public Building and Related Furniture",
  "2540": "Partitions, Shelvg, Lockers, & Office & Store Fixtures",
  "2590": "Miscellaneous Furniture and Fixtures",
  "2600": "Papers and Allied Products",
  "2611": "Pulp Mills",
  "2621": "Paper Mills",
  "2631": "Paperboard Mills",
  "2650": "Paperboard Containers and Boxes",
  "2670": "Converted Paper and Paperboard Prods (No Containers/Boxes)",
  "2711": "Newspapers: Publishing or Publishing and Printing",
  "2721": "Periodicals: Publishing or Publishing and Printing",
  "2731": "Books: Publishing or Publishing and Printing",
  "2732": "Book Printing",
  "2741": "Miscellaneous Publishing",
  "2750": "Commercial Printing",
  "2761": "Manifold Business Forms",
  "2771": "Greeting Cards",
  "2780": "Blankbooks, Looseleaf Binders and Bookbinding and Related Work",
  "2790": "Service Industries for the Printing Trade",
  "2800": "Chemicals and Allied Products",
  "2810": "Industrial Inorganic Chemicals",
  "2820": "Plastic Material, Synth Resin/Rubber, Cellulos (No Glass)",
  "2821": "Plastic Materials, Synth Resins & Nonvulcan Elastomers",
  "2833": "Medicinal Chemicals and Botanical Products",
  "2834": "Pharmaceutical Preparations",
  "2835": "In Vitro and In Vivo Diagnostic Substances",
  "2836": "Biological Products (No Diagnostic Substances)",
  "2840": "Soap, Detergents, Cleaning Preparations, Perfumes, Cosmetics",
  "2842": "Specialty Cleaning, Polishing and Sanitation Preparations",
  "2844": "Perfumes, Cosmetics and Other Toilet Preparations",
  "2851": "Paints, Varnishes, Lacquers, Enamels and Allied Products",
  "2860": "Industrial Organic Chemicals",
  "2870": "Agricultural Chemicals",
  "2890": "Miscellaneous Chemical Products",
  "2891": "Adhesives and Sealants",
  "2911": "Petroleum Refining",
  "2950": "Asphalt Paving and Roofing Materials",
  "2990": "Miscellaneous Products of Petroleum and Coal",
  "3011": "Tires and Inner Tubes",
  "3021": "Rubber and Plastics Footwear",
  "3050": "Gaskets, Packg & Sealg Devices & Rubber & Plastics Hose",
  "3060": "Fabricated Rubber Products",
  "3080": "Miscellaneous Plastics Products",
  "3081": "Unsupported Plastics Film and Sheet",
  "3086": "Plastics Foam Products",
  "3089": "Plastics Products",
  "3100": "Leather and Leather Products",
  "3140": "Footwear (No Rubber)",
  "3211": "Flat Glass",
  "3220": "Glass and Glassware, Pressed or Blown",
  "3221": "Glass Containers",
  "3231": "Glass Products, Made of Purchased Glass",
  "3241": "Cement, Hydraulic",
  "3250": "Structural Clay Products",
  "3260": "Pottery and Related Products",
  "3270": "Concrete, Gypsum and Plaster Products",
  "3272": "Concrete Products",
  "3281": "Cut Stone and Stone Products",
  "3290": "Abrasive, Asbestos and Miscellaneous Nonmetallic Mineral Prods",
  "3310": "Steel Works, Blast Furnaces and Rolling and Finishing Mills",
  "3312": "Steel Works, Blast Furnaces & Rolling Mills (Coke Ovens)",
  "3317": "Steel Pipe and Tubes",
  "3320": "Iron and Steel Foundries",
  "3330": "Primary Smelting and Refining of Nonferrous Metals",
  "3334": "Primary Production of Aluminum",
  "3341": "Secondary Smelting and Refining of Nonferrous Metals",
  "3350": "Rolling Drawing and Extruding of Nonferrous Metals",
  "3357": "Drawing and Insulating of Nonferrous Wire",
  "3360": "Nonferrous Foundries (Castings)",
  "3390": "Miscellaneous Primary Metal Products",
  "3411": "Metal Cans",
  "3412": "Metal Shipping Barrels, Drums, Kegs and Pails",
  "3420": "Cutlery, Handtools and General Hardware",
  "3430": "Heating Equip, Except Elec & Warm Air; & Plumbing Fixtures",
  "3433": "Heating Equipment (No Electric or Warm Air Furnaces)",
  "3440": "Fabricated Structural Metal Products",
  "3442": "Metal Doors, Sash, Frames, Moldings and Trim",
  "3443": "Fabricated Plate Work (Boiler Shops)",
  "3444": "Sheet Metal Work",
  "3448": "Prefabricated Metal Buildings and Components",
  "3451": "Screw Machine Products",
  "3452": "Bolts, Nuts, Screws, Rivets and Washers",
  "3460": "Metal Forgings and Stampings",
  "3470": "Coating, Engraving and Allied Services",
  "3480": "Ordnance and Accessories (No Vehicles/Guided Missiles)",
  "3490": "Miscellaneous Fabricated Metal Products",
  "3510": "Engines and Turbines",
  "3523": "Farm Machinery and Equipment",
  "3524": "Lawn and Garden Tractors and Home Lawn and Gardens Equip",
  "3530": "Construction, Mining and Materials Handling Machinery and Equip",
  "3531": "Construction Machinery and Equip",
  "3532": "Mining Machinery and Equip (No Oil and Gas Field Mach and Equip)",
  "3533": "Oil and Gas Field Machinery and Equipment",
  "3537": "Industrial Trucks, Tractors, Trailors and Stackers",
  "3540": "Metalworkg Machinery and Equipment",
  "3541": "Machine Tools, Metal Cutting Types",
  "3550": "Special Industry Machinery (No Metalworking Machinery)",
  "3555": "Printing Trades Machinery and Equipment",
  "3559": "Special Industry Machinery",
  "3560": "General Industrial Machinery and Equipment",
  "3561": "Pumps and Pumping Equipment",
  "3562": "Ball and Roller Bearings",
  "3564": "Industrial and Commercial Fans and Blowers and Air Purifying Equip",
  "3567": "Industrial Process Furnaces and Ovens",
  "3569": "General Industrial Machinery and Equipment",
  "3570": "Computer and Office Equipment",
  "3571": "Electronic Computers",
  "3572": "Computer Storage Devices",
  "3575": "Computer Terminals",
  "3576": "Computer Communications Equipment",
  "3577": "Computer Peripheral Equipment",
  "3578": "Calculating and Accounting Machines (No Electronic Computers)",
  "3579": "Office Machines",
  "3580": "Refrigeration and Service Industry Machinery",
  "3585": "Air-Cond & Warm Air Heating Equip & Comm & Indl Refrig Equip",
  "3590": "Miscellaneous Industrial and Commercial Machinery and Equipment",
  "3600": "Electronic and Other Electrical Equipment (No Computer Equip)",
  "3612": "Power, Distribution and Specialty Transformers",
  "3613": "Switchgear and Switchboard Apparatus",
  "3620": "Electrical Industrial Apparatus",
  "3621": "Motors and Generators",
  "3630": "Household Appliances",
  "3634": "Electric Housewares and Fans",
  "3640": "Electric Lighting and Wiring Equipment",
  "3651": "Household Audio and Video Equipment",
  "3652": "Phonograph Records and Prerecorded Audio Tapes and Disks",
  "3661": "Telephone and Telegraph Apparatus",
  "3663": "Radio and Television Broadcasting and Communications Equipment",
  "3669": "Communications Equipment",
  "3670": "Electronic Components and Accessories",
  "3672": "Printed Circuit Boards",
  "3674": "Semiconductors and Related Devices",
  "3677": "Electronic Coils, Transformers and Other Inductors",
  "3678": "Electronic Connectors",
  "3679": "Electronic Components",
  "3690": "Miscellaneous Electrical Machinery, Equipment and Supplies",
  "3695": "Magnetic and Optical Recording Media",
  "3711": "Motor Vehicles and Passenger Car Bodies",
  "3713": "Truck and Bus Bodies",
  "3714": "Motor Vehicle Parts and Accessories",
  "3715": "Truck Trailers",
  "3716": "Motor Homes",
  "3720": "Aircraft and Parts",
  "3721": "Aircraft",
  "3724": "Aircraft Engines and Engine Parts",
  "3728": "Aircraft Parts and Auxiliary Equipment",
  "3730": "Ship and Boat Building and Repairing",
  "3743": "Railroad Equipment",
  "3751": "Motorcycles, Bicycles and Parts",
  "3760": "Guided Missiles and Space Vehicles and Parts",
  "3790": "Miscellaneous Transportation Equipment",
  "3812": "Search, Detection, Navigation, Guidance, Aeronautical Sys",
  "3821": "Laboratory Apparatus and Furniture",
  "3822": "Auto Controls for Regulating Residential & Comml Environments",
  "3823": "Industrial Instruments for Measurement, Display, and Control",
  "3824": "Totalizing Fluid Meters and Counting Devices",
  "3825": "Instruments for Meas and Testing of Electricity and Elec Signals",
  "3826": "Laboratory Analytical Instruments",
  "3827": "Optical Instruments and Lenses",
  "3829": "Measuring and Controlling Devices",
  "3841": "Surgical and Medical Instruments and Apparatus",
  "3842": "Orthopedic, Prosthetic and Surgical Appliances and Supplies",
  "3843": "Dental Equipment and Supplies",
  "3844": "X-Ray Apparatus and Tubes and Related Irradiation Apparatus",
  "3845": "Electromedical and Electrotherapeutic Apparatus",
  "3851": "Ophthalmic Goods",
  "3861": "Photographic Equipment and Supplies",
  "3873": "Watches, Clocks, Clockwork Operated Devices/Parts",
  "3910": "Jewelry, Silverware and Plated Ware",
  "3911": "Jewelry, Precious Metal",
  "3931": "Musical Instruments",
  "3942": "Dolls and Stuffed Toys",
  "3944": "Games, Toys and Children's Vehicles (No Dolls & Bicycles)",
  "3949": "Sporting and Athletic Goods",
  "3950": "Pens, Pencils and Other Artists' Materials",
  "3960": "Costume Jewelry and Novelties",
  "3990": "Miscellaneous Manufacturing Industries",

  // Transportation, Communications, Electric, Gas and Sanitary service (4000-4999)
  "4011": "Railroads, Line-Haul Operating",
  "4013": "Railroad Switching and Terminal Establishments",
  "4100": "Local and Suburban Transit and Interurban Highway Transportation",
  "4210": "Trucking and Courier Services (No Air)",
  "4213": "Trucking (No Local)",
  "4220": "Public Warehousing and Storage",
  "4231": "Terminal and Joint Terminal Maintenance Facilities for Motor Freight Transportation",
  "4400": "Water Transportation",
  "4412": "Deep Sea Foreign Transportation of Freight",
  "4512": "Air Transportation, Scheduled",
  "4513": "Air Courier Services",
  "4522": "Air Transportation, Nonscheduled",
  "4581": "Airports, Flying Fields and Airport Terminal Services",
  "4610": "Pipe Lines (No Natural Gas)",
  "4700": "Transportation Services",
  "4731": "Arrangement of Transportation of Freight and Cargo",
  "4812": "Radiotelephone Communications",
  "4813": "Telephone Communications (No Radiotelephone)",
  "4822": "Telegraph and Other Message Communications",
  "4832": "Radio Broadcasting Stations",
  "4833": "Television Broadcasting Stations",
  "4841": "Cable and Other Pay Television Services",
  "4899": "Communications Services",
  "4900": "Electric, Gas and Sanitary Services",
  "4911": "Electric Services",
  "4922": "Natural Gas Transmission",
  "4923": "Natural Gas Transmission and Distribution",
  "4924": "Natural Gas Distribution",
  "4931": "Electric and Other Services Combined",
  "4932": "Gas and Other Services Combined",
  "4941": "Water Supply",
  "4950": "Sanitary Services",
  "4953": "Refuse Systems",
  "4955": "Hazardous Waste Management",
  "4961": "Steam and Air-Conditioning Supply",
  "4991": "Cogeneration Services and Small Power Producers",

  // Wholesale Trade (5000-5199)
  "5000": "Wholesale - Durable Goods",
  "5010": "Wholesale - Motor Vehicles and Motor Vehicle Parts and Supplies",
  "5013": "Wholesale - Motor Vehicle Supplies and New Parts",
  "5020": "Wholesale - Furniture and Home Furnishings",
  "5030": "Wholesale - Lumber and Other Construction Materials",
  "5031": "Wholesale - Lumber, Plywood, Millwork and Wood Panels",
  "5040": "Wholesale - Professional and Commercial Equipment and Supplies",
  "5045": "Wholesale - Computers and Peripheral Equipment and Software",
  "5047": "Wholesale - Medical, Dental and Hospital Equipment and Supplies",
  "5050": "Wholesale - Metals and Minerals (No Petroleum)",
  "5051": "Wholesale - Metals Service Centers and Offices",
  "5060": "Wholesale - Electrical Goods",
  "5063": "Wholesale - Electrical Apparatus and Equipment, Wiring Supplies",
  "5064": "Wholesale - Electrical Appliances, TV and Radio Sets",
  "5065": "Wholesale - Electronic Parts and Equipment",
  "5070": "Wholesale - Hardware, Plumbing and Heating Equipment and Supplies",
  "5072": "Wholesale - Hardware",
  "5080": "Wholesale - Machinery, Equipment and Supplies",
  "5082": "Wholesale - Construction and Mining (No Petro) Machinery and Equip",
  "5084": "Wholesale - Industrial Machinery and Equipment",
  "5090": "Wholesale - Miscellaneous Durable Goods",
  "5094": "Wholesale - Jewelry, Watches, Precious Stones and Metals",
  "5099": "Wholesale - Durable Goods",
  "5110": "Wholesale - Paper and Paper Products",
  "5122": "Wholesale - Drugs, Proprietaries and Druggists' Sundries",
  "5130": "Wholesale - Apparel, Piece Goods and Notions",
  "5140": "Wholesale - Groceries and Related Products",
  "5141": "Wholesale - Groceries, General Line",
  "5150": "Wholesale - Farm Product Raw Materials",
  "5160": "Wholesale - Chemicals and Allied Products",
  "5171": "Wholesale - Petroleum Bulk Stations and Terminals",
  "5172": "Wholesale - Petroleum and Petroleum Products (No Bulk Stations)",
  "5180": "Wholesale - Beer, Wine and Distilled Alcoholic Beverages",
  "5190": "Wholesale - Miscellaneous Nondurable Goods",
  "5194": "Wholesale - Tobacco and Tobacco Products",

  // Retail Trade (5200-5999)
  "5200": "Retail - Building Materials, Hardware, Garden Supply",
  "5211": "Retail - Lumber and Other Building Materials Dealers",
  "5271": "Retail - Mobile Home Dealers",
  "5311": "Retail - Department Stores",
  "5331": "Retail - Variety Stores",
  "5399": "Retail - Miscellaneous General Merchandise Stores",
  "5400": "Retail - Food Stores",
  "5411": "Retail - Grocery Stores",
  "5412": "Retail - Convenience Stores",
  "5500": "Retail - Auto Dealers and Gasoline Stations",
  "5531": "Retail - Auto and Home Supply Stores",
  "5600": "Retail - Apparel and Accessory Stores",
  "5621": "Retail - Women's Clothing Stores",
  "5651": "Retail - Family Clothing Stores",
  "5661": "Retail - Shoe Stores",
  "5700": "Retail - Home Furniture, Furnishings and Equipment Stores",
  "5712": "Retail - Furniture Stores",
  "5731": "Retail - Radio, TV and Consumer Electronics Stores",
  "5734": "Retail - Computer and Computer Software Stores",
  "5735": "Retail - Record and Prerecorded Tape Stores",
  "5810": "Retail - Eating and Drinking Places",
  "5812": "Retail - Eating Places",
  "5900": "Retail - Miscellaneous Retail",
  "5912": "Retail - Drug Stores and Proprietary Stores",
  "5940": "Retail - Miscellaneous Shopping Goods Stores",
  "5944": "Retail - Jewelry Stores",
  "5945": "Retail - Hobby, Toy and Game Shops",
  "5960": "Retail - Nonstore Retailers",
  "5961": "Retail - Catalog and Mail-Order Houses",
  "5990": "Retail - Retail Stores",

  // Finance, Insurance and Real Estate (6000-6799)
  "6021": "National Commercial Banks",
  "6022": "State Commercial Banks",
  "6029": "Commercial Banks",
  "6035": "Savings Institution, Federally Chartered",
  "6036": "Savings Institutions (No Federal Charter)",
  "6099": "Functions Related to Depository Banking",
  "6111": "Federal and Federally-Sponsored Credit Agencies",
  "6141": "Personal Credit Institutions",
  "6153": "Short-Term Business Credit Institutions (No Agric)",
  "6159": "Miscellaneous Business Credit Institutions",
  "6162": "Mortgage Bankers and Loan Correspondents",
  "6163": "Loan Brokers",
  "6172": "Finance Lessors",
  "6189": "Asset-Backed Securities",
  "6199": "Finance Services",
  "6200": "Security and Commodity Brokers, Dealers, Exchanges and Services",
  "6211": "Security Brokers, Dealers and Flotation Companies",
  "6221": "Commodity Contracts Brokers and Dealers",
  "6282": "Investment Advice",
  "6311": "Life Insurance",
  "6321": "Accident and Health Insurance",
  "6324": "Hospital and Medical Service Plans",
  "6331": "Fire, Marine and Casualty Insurance",
  "6351": "Surety Insurance",
  "6361": "Title Insurance",
  "6371": "Pension, Health and Welfare Funds",
  "6399": "Insurance Carriers",
  "6411": "Insurance Agents, Brokers and Service",
  "6500": "Real Estate",
  "6510": "Real Estate Operators (No Developers) and Lessors",
  "6512": "Operators of Nonresidential Buildings",
  "6513": "Operators of Apartment Buildings",
  "6519": "Lessors of Real Property",
  "6531": "Real Estate Agents and Managers (For Others)",
  "6532": "Real Estate Dealers (For Their Own Account)",
  "6552": "Land Subdividers and Developers (No Cemeteries)",
  "6770": "Blank Checks",
  "6792": "Oil Royalty Traders",
  "6794": "Patent Owners and Lessors",
  "6795": "Mineral Royalty Traders",
  "6798": "Real Estate Investment Trusts",
  "6799": "Investors",

  // Services (7000-8999)
  "7000": "Hotels, Rooming Houses, Camps and Other Lodging Places",
  "7011": "Hotels and Motels",
  "7200": "Services - Personal Services",
  "7310": "Services - Advertising",
  "7311": "Services - Advertising Agencies",
  "7320": "Services - Consumer Credit Reporting, Collection Agencies",
  "7330": "Services - Mailing, Reproduction, Commercial Art and Photography",
  "7331": "Services - Direct Mail Advertising Services",
  "7340": "Services - To Dwellings and Other Buildings",
  "7350": "Services - Miscellaneous Equipment Rental and Leasing",
  "7359": "Services - Equipment Rental and Leasing",
  "7361": "Services - Employment Agencies",
  "7363": "Services - Help Supply Services",
  "7370": "Services - Computer Programming, Data Processing, Etc.",
  "7371": "Services - Computer Programming Services",
  "7372": "Services - Prepackaged Software",
  "7373": "Services - Computer Integrated Systems Design",
  "7374": "Services - Computer Processing and Data Preparation",
  "7377": "Services - Computer Rental and Leasing",
  "7380": "Services - Miscellaneous Business Services",
  "7381": "Services - Detective, Guard and Armored Car Services",
  "7384": "Services - Photofinishing Laboratories",
  "7385": "Services - Telephone Interconnect Systems",
  "7389": "Services - Business Services",
  "7500": "Services - Automotive Repair, Services and Parking",
  "7510": "Services - Automotive Rentals (No Drivers)",
  "7600": "Services - Miscellaneous Repair Services",
  "7812": "Services - Motion Picture and Video Tape Production",
  "7819": "Services - Allied to Motion Picture Production",
  "7822": "Services - Motion Picture and Video Tape Distribution",
  "7829": "Services - Allied to Motion Picture Distribution",
  "7830": "Services - Motion Picture Theaters",
  "7841": "Services - Video Tape Rental",
  "7900": "Services - Amusement and Recreation Services",
  "7948": "Services - Racing, Including Track Operation",
  "7990": "Services - Miscellaneous Amusement and Recreation",
  "7997": "Services - Membership Sports and Recreation Clubs",
  "8000": "Services - Health Services",
  "8011": "Services - Offices and Clinics of Doctors of Medicine",
  "8050": "Services - Nursing and Personal Care Facilities",
  "8051": "Services - Skilled Nursing Care Facilities",
  "8060": "Services - Hospitals",
  "8062": "Services - General Medical and Surgical Hospitals",
  "8071": "Services - Medical Laboratories",
  "8082": "Services - Home Health Care Services",
  "8090": "Services - Miscellaneous Health and Allied Services",
  "8093": "Services - Specialty Outpatient Facilities",
  "8111": "Services - Legal Services",
  "8200": "Services - Educational Services",
  "8300": "Services - Social Services",
  "8351": "Services - Child Day Care Services",
  "8600": "Services - Membership Organizations",
  "8700": "Services - Engineering, Accounting, Research, Management",
  "8711": "Services - Engineering Services",
  "8731": "Services - Commercial Physical and Biological Research",
  "8734": "Services - Testing Laboratories",
  "8741": "Services - Management Services",
  "8742": "Services - Management Consulting Services",
  "8744": "Services - Facilities Support Management Services",
  "8880": "Services - American Depositary Receipts",
  "8888": "Services - Foreign Governments",
  "8900": "Services - Services",

  // Public Administration (9000-9999)
  "9721": "International Affairs",
  "9995": "Non-Operating Establishments",
} as const;

/**
 * Get SIC code description
 * @param code - 4-digit SIC code as string
 * @returns Description or undefined if not found
 */
export function getSICDescription(code: string | undefined | null): string | undefined {
  if (!code) return undefined;
  return SIC_CODES[code];
}

/**
 * Type for valid SIC codes
 */
export type SICCode = keyof typeof SIC_CODES;
