/**
 * Standard Industrial Classification (SIC) Codes
 * Source: https://www.sec.gov/search-filings/standard-industrial-classification-sic-code-list
 *
 * Generated from SEC SIC code table: code, office, and industry title.
 */

export interface SICCodeMetadata {
  office: string;
  industryTitle: string;
}

export const SIC_CODE_METADATA = {
  "100": { office: "Industrial Applications and Services", industryTitle: "AGRICULTURAL PRODUCTION-CROPS" },
  "200": { office: "Industrial Applications and Services", industryTitle: "AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES" },
  "700": { office: "Industrial Applications and Services", industryTitle: "AGRICULTURAL SERVICES" },
  "800": { office: "Industrial Applications and Services", industryTitle: "FORESTRY" },
  "900": { office: "Industrial Applications and Services", industryTitle: "FISHING, HUNTING AND TRAPPING" },
  "1000": { office: "Office of Energy & Transportation", industryTitle: "METAL MINING" },
  "1040": { office: "Office of Energy & Transportation", industryTitle: "GOLD AND SILVER ORES" },
  "1090": { office: "Office of Energy & Transportation", industryTitle: "MISCELLANEOUS METAL ORES" },
  "1220": { office: "Office of Energy & Transportation", industryTitle: "BITUMINOUS COAL & LIGNITE MINING" },
  "1221": { office: "Office of Energy & Transportation", industryTitle: "BITUMINOUS COAL & LIGNITE SURFACE MINING" },
  "1311": { office: "Office of Energy & Transportation", industryTitle: "CRUDE PETROLEUM & NATURAL GAS" },
  "1381": { office: "Office of Energy & Transportation", industryTitle: "DRILLING OIL & GAS WELLS" },
  "1382": { office: "Office of Energy & Transportation", industryTitle: "OIL & GAS FIELD EXPLORATION SERVICES" },
  "1389": { office: "Office of Energy & Transportation", industryTitle: "OIL & GAS FIELD SERVICES, NEC" },
  "1400": { office: "Office of Energy & Transportation", industryTitle: "MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)" },
  "1520": { office: "Office of Real Estate & Construction", industryTitle: "GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS" },
  "1531": { office: "Office of Real Estate & Construction", industryTitle: "OPERATIVE BUILDERS" },
  "1540": { office: "Office of Real Estate & Construction", industryTitle: "GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS" },
  "1600": { office: "Office of Real Estate & Construction", industryTitle: "HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS" },
  "1623": { office: "Office of Real Estate & Construction", industryTitle: "WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION" },
  "1700": { office: "Office of Real Estate & Construction", industryTitle: "CONSTRUCTION - SPECIAL TRADE CONTRACTORS" },
  "1731": { office: "Office of Real Estate & Construction", industryTitle: "ELECTRICAL WORK" },
  "2000": { office: "Office of Manufacturing", industryTitle: "FOOD AND KINDRED PRODUCTS" },
  "2011": { office: "Office of Manufacturing", industryTitle: "MEAT PACKING PLANTS" },
  "2013": { office: "Office of Manufacturing", industryTitle: "SAUSAGES & OTHER PREPARED MEAT PRODUCTS" },
  "2015": { office: "Office of Manufacturing", industryTitle: "POULTRY SLAUGHTERING AND PROCESSING" },
  "2020": { office: "Office of Manufacturing", industryTitle: "DAIRY PRODUCTS" },
  "2024": { office: "Office of Manufacturing", industryTitle: "ICE CREAM & FROZEN DESSERTS" },
  "2030": { office: "Office of Manufacturing", industryTitle: "CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES" },
  "2033": { office: "Office of Manufacturing", industryTitle: "CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES" },
  "2040": { office: "Office of Manufacturing", industryTitle: "GRAIN MILL PRODUCTS" },
  "2050": { office: "Office of Manufacturing", industryTitle: "BAKERY PRODUCTS" },
  "2052": { office: "Office of Manufacturing", industryTitle: "COOKIES & CRACKERS" },
  "2060": { office: "Office of Manufacturing", industryTitle: "SUGAR & CONFECTIONERY PRODUCTS" },
  "2070": { office: "Office of Manufacturing", industryTitle: "FATS & OILS" },
  "2080": { office: "Office of Manufacturing", industryTitle: "BEVERAGES" },
  "2082": { office: "Office of Manufacturing", industryTitle: "MALT BEVERAGES" },
  "2086": { office: "Office of Manufacturing", industryTitle: "BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS" },
  "2090": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS" },
  "2092": { office: "Office of Manufacturing", industryTitle: "PREPARED FRESH OR FROZEN FISH & SEAFOODS" },
  "2100": { office: "Office of Manufacturing", industryTitle: "TOBACCO PRODUCTS" },
  "2111": { office: "Office of Manufacturing", industryTitle: "CIGARETTES" },
  "2200": { office: "Office of Manufacturing", industryTitle: "TEXTILE MILL PRODUCTS" },
  "2211": { office: "Office of Manufacturing", industryTitle: "BROADWOVEN FABRIC MILLS, COTTON" },
  "2221": { office: "Office of Manufacturing", industryTitle: "BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK" },
  "2250": { office: "Office of Manufacturing", industryTitle: "KNITTING MILLS" },
  "2253": { office: "Office of Manufacturing", industryTitle: "KNIT OUTERWEAR MILLS" },
  "2273": { office: "Office of Manufacturing", industryTitle: "CARPETS & RUGS" },
  "2300": { office: "Office of Manufacturing", industryTitle: "APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL" },
  "2320": { office: "Office of Manufacturing", industryTitle: "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS" },
  "2330": { office: "Office of Manufacturing", industryTitle: "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR" },
  "2340": { office: "Office of Manufacturing", industryTitle: "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS" },
  "2390": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS FABRICATED TEXTILE PRODUCTS" },
  "2400": { office: "Office of Manufacturing", industryTitle: "LUMBER & WOOD PRODUCTS (NO FURNITURE)" },
  "2421": { office: "Office of Manufacturing", industryTitle: "SAWMILLS & PLANTING MILLS, GENERAL" },
  "2430": { office: "Office of Manufacturing", industryTitle: "MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS" },
  "2451": { office: "Office of Manufacturing", industryTitle: "MOBILE HOMES" },
  "2452": { office: "Office of Manufacturing", industryTitle: "PREFABRICATED WOOD BLDGS & COMPONENTS" },
  "2510": { office: "Office of Manufacturing", industryTitle: "HOUSEHOLD FURNITURE" },
  "2511": { office: "Office of Manufacturing", industryTitle: "WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)" },
  "2520": { office: "Office of Manufacturing", industryTitle: "OFFICE FURNITURE" },
  "2522": { office: "Office of Manufacturing", industryTitle: "OFFICE FURNITURE (NO WOOD)" },
  "2531": { office: "Office of Manufacturing", industryTitle: "PUBLIC BLDG & RELATED FURNITURE" },
  "2540": { office: "Office of Manufacturing", industryTitle: "PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES" },
  "2590": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS FURNITURE & FIXTURES" },
  "2600": { office: "Office of Manufacturing", industryTitle: "PAPERS & ALLIED PRODUCTS" },
  "2611": { office: "Office of Manufacturing", industryTitle: "PULP MILLS" },
  "2621": { office: "Office of Manufacturing", industryTitle: "PAPER MILLS" },
  "2631": { office: "Office of Manufacturing", industryTitle: "PAPERBOARD MILLS" },
  "2650": { office: "Office of Manufacturing", industryTitle: "PAPERBOARD CONTAINERS & BOXES" },
  "2670": { office: "Office of Manufacturing", industryTitle: "CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)" },
  "2673": { office: "Office of Manufacturing", industryTitle: "PLASTICS, FOIL & COATED PAPER BAGS" },
  "2711": { office: "Office of Manufacturing", industryTitle: "NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING" },
  "2721": { office: "Office of Manufacturing", industryTitle: "PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING" },
  "2731": { office: "Office of Manufacturing", industryTitle: "BOOKS: PUBLISHING OR PUBLISHING & PRINTING" },
  "2732": { office: "Office of Manufacturing", industryTitle: "BOOK PRINTING" },
  "2741": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS PUBLISHING" },
  "2750": { office: "Office of Manufacturing", industryTitle: "COMMERCIAL PRINTING" },
  "2761": { office: "Office of Manufacturing", industryTitle: "MANIFOLD BUSINESS FORMS" },
  "2771": { office: "Office of Manufacturing", industryTitle: "GREETING CARDS" },
  "2780": { office: "Office of Manufacturing", industryTitle: "BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK" },
  "2790": { office: "Office of Manufacturing", industryTitle: "SERVICE INDUSTRIES FOR THE PRINTING TRADE" },
  "2800": { office: "Industrial Applications and Services", industryTitle: "CHEMICALS & ALLIED PRODUCTS" },
  "2810": { office: "Industrial Applications and Services", industryTitle: "INDUSTRIAL INORGANIC CHEMICALS" },
  "2820": { office: "Industrial Applications and Services", industryTitle: "PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)" },
  "2821": { office: "Industrial Applications and Services", industryTitle: "PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS" },
  "2833": { office: "Office of Life Sciences", industryTitle: "MEDICINAL CHEMICALS & BOTANICAL PRODUCTS" },
  "2834": { office: "Office of Life Sciences", industryTitle: "PHARMACEUTICAL PREPARATIONS" },
  "2835": { office: "Office of Life Sciences", industryTitle: "IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES" },
  "2836": { office: "Office of Life Sciences", industryTitle: "BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)" },
  "2840": { office: "Industrial Applications and Services", industryTitle: "SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS" },
  "2842": { office: "Industrial Applications and Services", industryTitle: "SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS" },
  "2844": { office: "Industrial Applications and Services", industryTitle: "PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS" },
  "2851": { office: "Industrial Applications and Services", industryTitle: "PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS" },
  "2860": { office: "Industrial Applications and Services", industryTitle: "INDUSTRIAL ORGANIC CHEMICALS" },
  "2870": { office: "Industrial Applications and Services", industryTitle: "AGRICULTURAL CHEMICALS" },
  "2890": { office: "Industrial Applications and Services", industryTitle: "MISCELLANEOUS CHEMICAL PRODUCTS" },
  "2891": { office: "Industrial Applications and Services", industryTitle: "ADHESIVES & SEALANTS" },
  "2911": { office: "Office of Energy & Transportation", industryTitle: "PETROLEUM REFINING" },
  "2950": { office: "Office of Energy & Transportation", industryTitle: "ASPHALT PAVING & ROOFING MATERIALS" },
  "2990": { office: "Office of Energy & Transportation", industryTitle: "MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL" },
  "3011": { office: "Office of Manufacturing", industryTitle: "TIRES & INNER TUBES" },
  "3021": { office: "Office of Manufacturing", industryTitle: "RUBBER & PLASTICS FOOTWEAR" },
  "3050": { office: "Office of Manufacturing", industryTitle: "GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE" },
  "3060": { office: "Office of Manufacturing", industryTitle: "FABRICATED RUBBER PRODUCTS, NEC" },
  "3080": { office: "Industrial Applications and Services", industryTitle: "MISCELLANEOUS PLASTICS PRODUCTS" },
  "3081": { office: "Industrial Applications and Services", industryTitle: "UNSUPPORTED PLASTICS FILM & SHEET" },
  "3086": { office: "Industrial Applications and Services", industryTitle: "PLASTICS FOAM PRODUCTS" },
  "3089": { office: "Industrial Applications and Services", industryTitle: "PLASTICS PRODUCTS, NEC" },
  "3100": { office: "Office of Manufacturing", industryTitle: "LEATHER & LEATHER PRODUCTS" },
  "3140": { office: "Office of Manufacturing", industryTitle: "FOOTWEAR, (NO RUBBER)" },
  "3211": { office: "Office of Manufacturing", industryTitle: "FLAT GLASS" },
  "3220": { office: "Office of Manufacturing", industryTitle: "GLASS & GLASSWARE, PRESSED OR BLOWN" },
  "3221": { office: "Office of Manufacturing", industryTitle: "GLASS CONTAINERS" },
  "3231": { office: "Office of Manufacturing", industryTitle: "GLASS PRODUCTS, MADE OF PURCHASED GLASS" },
  "3241": { office: "Office of Manufacturing", industryTitle: "CEMENT, HYDRAULIC" },
  "3250": { office: "Office of Manufacturing", industryTitle: "STRUCTURAL CLAY PRODUCTS" },
  "3260": { office: "Office of Manufacturing", industryTitle: "POTTERY & RELATED PRODUCTS" },
  "3270": { office: "Office of Manufacturing", industryTitle: "CONCRETE, GYPSUM & PLASTER PRODUCTS" },
  "3272": { office: "Office of Manufacturing", industryTitle: "CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK" },
  "3281": { office: "Office of Manufacturing", industryTitle: "CUT STONE & STONE PRODUCTS" },
  "3290": { office: "Office of Manufacturing", industryTitle: "ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS" },
  "3310": { office: "Office of Manufacturing", industryTitle: "STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS" },
  "3312": { office: "Office of Manufacturing", industryTitle: "STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)" },
  "3317": { office: "Office of Manufacturing", industryTitle: "STEEL PIPE & TUBES" },
  "3320": { office: "Office of Manufacturing", industryTitle: "IRON & STEEL FOUNDRIES" },
  "3330": { office: "Office of Manufacturing", industryTitle: "PRIMARY SMELTING & REFINING OF NONFERROUS METALS" },
  "3334": { office: "Office of Manufacturing", industryTitle: "PRIMARY PRODUCTION OF ALUMINUM" },
  "3341": { office: "Office of Manufacturing", industryTitle: "SECONDARY SMELTING & REFINING OF NONFERROUS METALS" },
  "3350": { office: "Office of Manufacturing", industryTitle: "ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS" },
  "3357": { office: "Office of Manufacturing", industryTitle: "DRAWING & INSULATING OF NONFERROUS WIRE" },
  "3360": { office: "Office of Manufacturing", industryTitle: "NONFERROUS FOUNDRIES (CASTINGS)" },
  "3390": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS PRIMARY METAL PRODUCTS" },
  "3411": { office: "Office of Manufacturing", industryTitle: "METAL CANS" },
  "3412": { office: "Office of Manufacturing", industryTitle: "METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS" },
  "3420": { office: "Office of Manufacturing", industryTitle: "CUTLERY, HANDTOOLS & GENERAL HARDWARE" },
  "3430": { office: "Office of Manufacturing", industryTitle: "HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES" },
  "3433": { office: "Office of Manufacturing", industryTitle: "HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES" },
  "3440": { office: "Office of Manufacturing", industryTitle: "FABRICATED STRUCTURAL METAL PRODUCTS" },
  "3442": { office: "Office of Manufacturing", industryTitle: "METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM" },
  "3443": { office: "Office of Manufacturing", industryTitle: "FABRICATED PLATE WORK (BOILER SHOPS)" },
  "3444": { office: "Office of Manufacturing", industryTitle: "SHEET METAL WORK" },
  "3448": { office: "Office of Manufacturing", industryTitle: "PREFABRICATED METAL BUILDINGS & COMPONENTS" },
  "3451": { office: "Office of Manufacturing", industryTitle: "SCREW MACHINE PRODUCTS" },
  "3452": { office: "Office of Manufacturing", industryTitle: "BOLTS, NUTS, SCREWS, RIVETS & WASHERS" },
  "3460": { office: "Office of Manufacturing", industryTitle: "METAL FORGINGS & STAMPINGS" },
  "3470": { office: "Office of Manufacturing", industryTitle: "COATING, ENGRAVING & ALLIED SERVICES" },
  "3480": { office: "Office of Manufacturing", industryTitle: "ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)" },
  "3490": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS FABRICATED METAL PRODUCTS" },
  "3510": { office: "Office of Technology", industryTitle: "ENGINES & TURBINES" },
  "3523": { office: "Office of Technology", industryTitle: "FARM MACHINERY & EQUIPMENT" },
  "3524": { office: "Office of Technology", industryTitle: "LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP" },
  "3530": { office: "Office of Technology", industryTitle: "CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP" },
  "3531": { office: "Office of Technology", industryTitle: "CONSTRUCTION MACHINERY & EQUIP" },
  "3532": { office: "Office of Technology", industryTitle: "MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)" },
  "3533": { office: "Office of Energy & Transportation", industryTitle: "OIL & GAS FIELD MACHINERY & EQUIPMENT" },
  "3537": { office: "Office of Technology", industryTitle: "INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS" },
  "3540": { office: "Office of Technology", industryTitle: "METALWORKG MACHINERY & EQUIPMENT" },
  "3541": { office: "Office of Technology", industryTitle: "MACHINE TOOLS, METAL CUTTING TYPES" },
  "3550": { office: "Office of Technology", industryTitle: "SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)" },
  "3555": { office: "Office of Technology", industryTitle: "PRINTING TRADES MACHINERY & EQUIPMENT" },
  "3559": { office: "Office of Technology", industryTitle: "SPECIAL INDUSTRY MACHINERY, NEC" },
  "3560": { office: "Office of Technology", industryTitle: "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT" },
  "3561": { office: "Office of Technology", industryTitle: "PUMPS & PUMPING EQUIPMENT" },
  "3562": { office: "Office of Technology", industryTitle: "BALL & ROLLER BEARINGS" },
  "3564": { office: "Office of Technology", industryTitle: "INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP" },
  "3567": { office: "Office of Technology", industryTitle: "INDUSTRIAL PROCESS FURNACES & OVENS" },
  "3569": { office: "Office of Technology", industryTitle: "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC" },
  "3570": { office: "Office of Technology", industryTitle: "COMPUTER & OFFICE EQUIPMENT" },
  "3571": { office: "Office of Technology", industryTitle: "ELECTRONIC COMPUTERS" },
  "3572": { office: "Office of Technology", industryTitle: "COMPUTER STORAGE DEVICES" },
  "3575": { office: "Office of Technology", industryTitle: "COMPUTER TERMINALS" },
  "3576": { office: "Office of Technology", industryTitle: "COMPUTER COMMUNICATIONS EQUIPMENT" },
  "3577": { office: "Office of Technology", industryTitle: "COMPUTER PERIPHERAL EQUIPMENT, NEC" },
  "3578": { office: "Office of Technology", industryTitle: "CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)" },
  "3579": { office: "Office of Technology", industryTitle: "OFFICE MACHINES, NEC" },
  "3580": { office: "Office of Technology", industryTitle: "REFRIGERATION & SERVICE INDUSTRY MACHINERY" },
  "3585": { office: "Office of Technology", industryTitle: "AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP" },
  "3590": { office: "Office of Technology", industryTitle: "MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT" },
  "3600": { office: "Office of Manufacturing", industryTitle: "ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)" },
  "3612": { office: "Office of Manufacturing", industryTitle: "POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS" },
  "3613": { office: "Office of Manufacturing", industryTitle: "SWITCHGEAR & SWITCHBOARD APPARATUS" },
  "3620": { office: "Office of Manufacturing", industryTitle: "ELECTRICAL INDUSTRIAL APPARATUS" },
  "3621": { office: "Office of Manufacturing", industryTitle: "MOTORS & GENERATORS" },
  "3630": { office: "Office of Manufacturing", industryTitle: "HOUSEHOLD APPLIANCES" },
  "3634": { office: "Office of Manufacturing", industryTitle: "ELECTRIC HOUSEWARES & FANS" },
  "3640": { office: "Office of Manufacturing", industryTitle: "ELECTRIC LIGHTING & WIRING EQUIPMENT" },
  "3651": { office: "Office of Manufacturing", industryTitle: "HOUSEHOLD AUDIO & VIDEO EQUIPMENT" },
  "3652": { office: "Office of Manufacturing", industryTitle: "PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS" },
  "3661": { office: "Office of Manufacturing", industryTitle: "TELEPHONE & TELEGRAPH APPARATUS" },
  "3663": { office: "Office of Manufacturing", industryTitle: "RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT" },
  "3669": { office: "Office of Manufacturing", industryTitle: "COMMUNICATIONS EQUIPMENT, NEC" },
  "3670": { office: "Office of Manufacturing", industryTitle: "ELECTRONIC COMPONENTS & ACCESSORIES" },
  "3672": { office: "Office of Manufacturing", industryTitle: "PRINTED CIRCUIT BOARDS" },
  "3674": { office: "Office of Manufacturing", industryTitle: "SEMICONDUCTORS & RELATED DEVICES" },
  "3677": { office: "Office of Manufacturing", industryTitle: "ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS" },
  "3678": { office: "Office of Manufacturing", industryTitle: "ELECTRONIC CONNECTORS" },
  "3679": { office: "Office of Manufacturing", industryTitle: "ELECTRONIC COMPONENTS, NEC" },
  "3690": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES" },
  "3695": { office: "Office of Manufacturing", industryTitle: "MAGNETIC & OPTICAL RECORDING MEDIA" },
  "3711": { office: "Office of Manufacturing", industryTitle: "MOTOR VEHICLES & PASSENGER CAR BODIES" },
  "3713": { office: "Office of Manufacturing", industryTitle: "TRUCK & BUS BODIES" },
  "3714": { office: "Office of Manufacturing", industryTitle: "MOTOR VEHICLE PARTS & ACCESSORIES" },
  "3715": { office: "Office of Manufacturing", industryTitle: "TRUCK TRAILERS" },
  "3716": { office: "Office of Manufacturing", industryTitle: "MOTOR HOMES" },
  "3720": { office: "Office of Manufacturing", industryTitle: "AIRCRAFT & PARTS" },
  "3721": { office: "Office of Manufacturing", industryTitle: "AIRCRAFT" },
  "3724": { office: "Office of Manufacturing", industryTitle: "AIRCRAFT ENGINES & ENGINE PARTS" },
  "3728": { office: "Office of Manufacturing", industryTitle: "AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC" },
  "3730": { office: "Office of Manufacturing", industryTitle: "SHIP & BOAT BUILDING & REPAIRING" },
  "3743": { office: "Office of Manufacturing", industryTitle: "RAILROAD EQUIPMENT" },
  "3751": { office: "Office of Manufacturing", industryTitle: "MOTORCYCLES, BICYCLES & PARTS" },
  "3760": { office: "Office of Manufacturing", industryTitle: "GUIDED MISSILES & SPACE VEHICLES & PARTS" },
  "3790": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS TRANSPORTATION EQUIPMENT" },
  "3812": { office: "Office of Manufacturing", industryTitle: "SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS" },
  "3821": { office: "Industrial Applications and Services", industryTitle: "LABORATORY APPARATUS & FURNITURE" },
  "3822": { office: "Industrial Applications and Services", industryTitle: "AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS" },
  "3823": { office: "Industrial Applications and Services", industryTitle: "INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL" },
  "3824": { office: "Industrial Applications and Services", industryTitle: "TOTALIZING FLUID METERS & COUNTING DEVICES" },
  "3825": { office: "Industrial Applications and Services", industryTitle: "INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS" },
  "3826": { office: "Industrial Applications and Services", industryTitle: "LABORATORY ANALYTICAL INSTRUMENTS" },
  "3827": { office: "Industrial Applications and Services", industryTitle: "OPTICAL INSTRUMENTS & LENSES" },
  "3829": { office: "Industrial Applications and Services", industryTitle: "MEASURING & CONTROLLING DEVICES, NEC" },
  "3841": { office: "Industrial Applications and Services", industryTitle: "SURGICAL & MEDICAL INSTRUMENTS & APPARATUS" },
  "3842": { office: "Industrial Applications and Services", industryTitle: "ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES" },
  "3843": { office: "Industrial Applications and Services", industryTitle: "DENTAL EQUIPMENT & SUPPLIES" },
  "3844": { office: "Industrial Applications and Services", industryTitle: "X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS" },
  "3845": { office: "Industrial Applications and Services", industryTitle: "ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS" },
  "3851": { office: "Industrial Applications and Services", industryTitle: "OPHTHALMIC GOODS" },
  "3861": { office: "Industrial Applications and Services", industryTitle: "PHOTOGRAPHIC EQUIPMENT & SUPPLIES" },
  "3873": { office: "Industrial Applications and Services", industryTitle: "WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS" },
  "3910": { office: "Office of Manufacturing", industryTitle: "JEWELRY, SILVERWARE & PLATED WARE" },
  "3911": { office: "Office of Manufacturing", industryTitle: "JEWELRY, PRECIOUS METAL" },
  "3931": { office: "Office of Manufacturing", industryTitle: "MUSICAL INSTRUMENTS" },
  "3942": { office: "Office of Manufacturing", industryTitle: "DOLLS & STUFFED TOYS" },
  "3944": { office: "Office of Manufacturing", industryTitle: "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)" },
  "3949": { office: "Office of Manufacturing", industryTitle: "SPORTING & ATHLETIC GOODS, NEC" },
  "3950": { office: "Office of Manufacturing", industryTitle: "PENS, PENCILS & OTHER ARTISTS' MATERIALS" },
  "3960": { office: "Office of Manufacturing", industryTitle: "COSTUME JEWELRY & NOVELTIES" },
  "3990": { office: "Office of Manufacturing", industryTitle: "MISCELLANEOUS MANUFACTURING INDUSTRIES" },
  "4011": { office: "Office of Energy & Transportation", industryTitle: "RAILROADS, LINE-HAUL OPERATING" },
  "4013": { office: "Office of Energy & Transportation", industryTitle: "RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS" },
  "4100": { office: "Office of Energy & Transportation", industryTitle: "LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS" },
  "4210": { office: "Office of Energy & Transportation", industryTitle: "TRUCKING & COURIER SERVICES (NO AIR)" },
  "4213": { office: "Office of Energy & Transportation", industryTitle: "TRUCKING (NO LOCAL)" },
  "4220": { office: "Office of Energy & Transportation", industryTitle: "PUBLIC WAREHOUSING & STORAGE" },
  "4231": { office: "Office of Energy & Transportation", industryTitle: "TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT" },
  "4400": { office: "Office of Energy & Transportation", industryTitle: "WATER TRANSPORTATION" },
  "4412": { office: "Office of Energy & Transportation", industryTitle: "DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT" },
  "4512": { office: "Office of Energy & Transportation", industryTitle: "AIR TRANSPORTATION, SCHEDULED" },
  "4513": { office: "Office of Energy & Transportation", industryTitle: "AIR COURIER SERVICES" },
  "4522": { office: "Office of Energy & Transportation", industryTitle: "AIR TRANSPORTATION, NONSCHEDULED" },
  "4581": { office: "Office of Energy & Transportation", industryTitle: "AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES" },
  "4610": { office: "Office of Energy & Transportation", industryTitle: "PIPE LINES (NO NATURAL GAS)" },
  "4700": { office: "Office of Energy & Transportation", industryTitle: "TRANSPORTATION SERVICES" },
  "4731": { office: "Office of Energy & Transportation", industryTitle: "ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO" },
  "4812": { office: "Office of Technology", industryTitle: "RADIOTELEPHONE COMMUNICATIONS" },
  "4813": { office: "Office of Technology", industryTitle: "TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)" },
  "4822": { office: "Office of Technology", industryTitle: "TELEGRAPH & OTHER MESSAGE COMMUNICATIONS" },
  "4832": { office: "Office of Technology", industryTitle: "RADIO BROADCASTING STATIONS" },
  "4833": { office: "Office of Technology", industryTitle: "TELEVISION BROADCASTING STATIONS" },
  "4841": { office: "Office of Technology", industryTitle: "CABLE & OTHER PAY TELEVISION SERVICES" },
  "4899": { office: "Office of Technology", industryTitle: "COMMUNICATIONS SERVICES, NEC" },
  "4900": { office: "Office of Energy & Transportation", industryTitle: "ELECTRIC, GAS & SANITARY SERVICES" },
  "4911": { office: "Office of Energy & Transportation", industryTitle: "ELECTRIC SERVICES" },
  "4922": { office: "Office of Energy & Transportation", industryTitle: "NATURAL GAS TRANSMISSION" },
  "4923": { office: "Office of Energy & Transportation", industryTitle: "NATURAL GAS TRANSMISISON & DISTRIBUTION" },
  "4924": { office: "Office of Energy & Transportation", industryTitle: "NATURAL GAS DISTRIBUTION" },
  "4931": { office: "Office of Energy & Transportation", industryTitle: "ELECTRIC & OTHER SERVICES COMBINED" },
  "4932": { office: "Office of Energy & Transportation", industryTitle: "GAS & OTHER SERVICES COMBINED" },
  "4941": { office: "Office of Energy & Transportation", industryTitle: "WATER SUPPLY" },
  "4950": { office: "Office of Energy & Transportation", industryTitle: "SANITARY SERVICES" },
  "4953": { office: "Office of Energy & Transportation", industryTitle: "REFUSE SYSTEMS" },
  "4955": { office: "Office of Energy & Transportation", industryTitle: "HAZARDOUS WASTE MANAGEMENT" },
  "4961": { office: "Office of Energy & Transportation", industryTitle: "STEAM & AIR-CONDITIONING SUPPLY" },
  "4991": { office: "Office of Energy & Transportation", industryTitle: "COGENERATION SERVICES & SMALL POWER PRODUCERS" },
  "5000": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-DURABLE GOODS" },
  "5010": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES" },
  "5013": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS" },
  "5020": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-FURNITURE & HOME FURNISHINGS" },
  "5030": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS" },
  "5031": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS" },
  "5040": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES" },
  "5045": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE" },
  "5047": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES" },
  "5050": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-METALS & MINERALS (NO PETROLEUM)" },
  "5051": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-METALS SERVICE CENTERS & OFFICES" },
  "5063": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES" },
  "5064": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS" },
  "5065": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC" },
  "5070": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES" },
  "5072": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-HARDWARE" },
  "5080": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES" },
  "5082": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP" },
  "5084": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT" },
  "5090": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MISC DURABLE GOODS" },
  "5094": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS" },
  "5099": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-DURABLE GOODS, NEC" },
  "5110": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-PAPER & PAPER PRODUCTS" },
  "5122": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES" },
  "5130": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-APPAREL, PIECE GOODS & NOTIONS" },
  "5140": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-GROCERIES & RELATED PRODUCTS" },
  "5141": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-GROCERIES, GENERAL LINE" },
  "5150": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-FARM PRODUCT RAW MATERIALS" },
  "5160": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-CHEMICALS & ALLIED PRODUCTS" },
  "5171": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS" },
  "5172": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)" },
  "5180": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES" },
  "5190": { office: "Office of Trade & Services", industryTitle: "WHOLESALE-MISCELLANEOUS NONDURABLE GOODS" },
  "5200": { office: "Office of Trade & Services", industryTitle: "RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY" },
  "5211": { office: "Office of Trade & Services", industryTitle: "RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS" },
  "5271": { office: "Office of Trade & Services", industryTitle: "RETAIL-MOBILE HOME DEALERS" },
  "5311": { office: "Office of Trade & Services", industryTitle: "RETAIL-DEPARTMENT STORES" },
  "5331": { office: "Office of Trade & Services", industryTitle: "RETAIL-VARIETY STORES" },
  "5399": { office: "Office of Trade & Services", industryTitle: "RETAIL-MISC GENERAL MERCHANDISE STORES" },
  "5400": { office: "Office of Trade & Services", industryTitle: "RETAIL-FOOD STORES" },
  "5411": { office: "Office of Trade & Services", industryTitle: "RETAIL-GROCERY STORES" },
  "5412": { office: "Office of Trade & Services", industryTitle: "RETAIL-CONVENIENCE STORES" },
  "5500": { office: "Office of Trade & Services", industryTitle: "RETAIL-AUTO DEALERS & GASOLINE STATIONS" },
  "5531": { office: "Office of Trade & Services", industryTitle: "RETAIL-AUTO & HOME SUPPLY STORES" },
  "5600": { office: "Office of Trade & Services", industryTitle: "RETAIL-APPAREL & ACCESSORY STORES" },
  "5621": { office: "Office of Trade & Services", industryTitle: "RETAIL-WOMEN'S CLOTHING STORES" },
  "5651": { office: "Office of Trade & Services", industryTitle: "RETAIL-FAMILY CLOTHING STORES" },
  "5661": { office: "Office of Trade & Services", industryTitle: "RETAIL-SHOE STORES" },
  "5700": { office: "Office of Trade & Services", industryTitle: "RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES" },
  "5712": { office: "Office of Trade & Services", industryTitle: "RETAIL-FURNITURE STORES" },
  "5731": { office: "Office of Trade & Services", industryTitle: "RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES" },
  "5734": { office: "Office of Trade & Services", industryTitle: "RETAIL-COMPUTER & COMPUTER SOFTWARE STORES" },
  "5735": { office: "Office of Trade & Services", industryTitle: "RETAIL-RECORD & PRERECORDED TAPE STORES" },
  "5810": { office: "Office of Trade & Services", industryTitle: "RETAIL-EATING & DRINKING PLACES" },
  "5812": { office: "Office of Trade & Services", industryTitle: "RETAIL-EATING PLACES" },
  "5900": { office: "Office of Trade & Services", industryTitle: "RETAIL-MISCELLANEOUS RETAIL" },
  "5912": { office: "Office of Trade & Services", industryTitle: "RETAIL-DRUG STORES AND PROPRIETARY STORES" },
  "5940": { office: "Office of Trade & Services", industryTitle: "RETAIL-MISCELLANEOUS SHOPPING GOODS STORES" },
  "5944": { office: "Office of Trade & Services", industryTitle: "RETAIL-JEWELRY STORES" },
  "5945": { office: "Office of Trade & Services", industryTitle: "RETAIL-HOBBY, TOY & GAME SHOPS" },
  "5960": { office: "Office of Trade & Services", industryTitle: "RETAIL-NONSTORE RETAILERS" },
  "5961": { office: "Office of Trade & Services", industryTitle: "RETAIL-CATALOG & MAIL-ORDER HOUSES" },
  "5990": { office: "Office of Trade & Services", industryTitle: "RETAIL-RETAIL STORES, NEC" },
  "6021": { office: "Office of Finance", industryTitle: "NATIONAL COMMERCIAL BANKS" },
  "6022": { office: "Office of Finance", industryTitle: "STATE COMMERCIAL BANKS" },
  "6029": { office: "Office of Finance", industryTitle: "COMMERCIAL BANKS, NEC" },
  "6035": { office: "Office of Finance", industryTitle: "SAVINGS INSTITUTION, FEDERALLY CHARTERED" },
  "6036": { office: "Office of Finance", industryTitle: "SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED" },
  "6099": { office: "Office of Finance", industryTitle: "FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC" },
  "6111": { office: "Office of Finance", industryTitle: "FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES" },
  "6141": { office: "Office of Finance", industryTitle: "PERSONAL CREDIT INSTITUTIONS" },
  "6153": { office: "Office of Finance", industryTitle: "SHORT-TERM BUSINESS CREDIT INSTITUTIONS" },
  "6159": { office: "Office of Finance", industryTitle: "MISCELLANEOUS BUSINESS CREDIT INSTITUTION" },
  "6162": { office: "Office of Finance", industryTitle: "MORTGAGE BANKERS & LOAN CORRESPONDENTS" },
  "6163": { office: "Office of Finance", industryTitle: "LOAN BROKERS" },
  "6172": { office: "Office of Finance", industryTitle: "FINANCE LESSORS" },
  "6189": { office: "Office of Structured Finance", industryTitle: "ASSET-BACKED SECURITIES" },
  "6199": { office: "Office of Finance or Office of Crypto Assets", industryTitle: "FINANCE SERVICES" },
  "6200": { office: "Office of Crypto Assets", industryTitle: "SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES" },
  "6211": { office: "Office of Finance or Office of Crypto Assets", industryTitle: "SECURITY BROKERS, DEALERS & FLOTATION COMPANIES" },
  "6221": { office: "Office of Crypto Assets", industryTitle: "COMMODITY CONTRACTS BROKERS & DEALERS" },
  "6282": { office: "Office of Finance", industryTitle: "INVESTMENT ADVICE" },
  "6311": { office: "Office of Finance", industryTitle: "LIFE INSURANCE" },
  "6321": { office: "Office of Finance", industryTitle: "ACCIDENT & HEALTH INSURANCE" },
  "6324": { office: "Office of Finance", industryTitle: "HOSPITAL & MEDICAL SERVICE PLANS" },
  "6331": { office: "Office of Finance", industryTitle: "FIRE, MARINE & CASUALTY INSURANCE" },
  "6351": { office: "Office of Finance", industryTitle: "SURETY INSURANCE" },
  "6361": { office: "Office of Finance", industryTitle: "TITLE INSURANCE" },
  "6399": { office: "Office of Finance", industryTitle: "INSURANCE CARRIERS, NEC" },
  "6411": { office: "Office of Finance", industryTitle: "INSURANCE AGENTS, BROKERS & SERVICE" },
  "6500": { office: "Office of Real Estate & Construction", industryTitle: "REAL ESTATE" },
  "6510": { office: "Office of Real Estate & Construction", industryTitle: "REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS" },
  "6512": { office: "Office of Real Estate & Construction", industryTitle: "OPERATORS OF NONRESIDENTIAL BUILDINGS" },
  "6513": { office: "Office of Real Estate & Construction", industryTitle: "OPERATORS OF APARTMENT BUILDINGS" },
  "6519": { office: "Office of Real Estate & Construction", industryTitle: "LESSORS OF REAL PROPERTY, NEC" },
  "6531": { office: "Office of Real Estate & Construction", industryTitle: "REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)" },
  "6532": { office: "Office of Real Estate & Construction", industryTitle: "REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)" },
  "6552": { office: "Office of Real Estate & Construction", industryTitle: "LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)" },
  "6770": { office: "Office of Real Estate & Construction", industryTitle: "BLANK CHECKS" },
  "6792": { office: "Office of Energy & Transportation", industryTitle: "OIL ROYALTY TRADERS" },
  "6794": { office: "Office of Real Estate & Construction", industryTitle: "PATENT OWNERS & LESSORS" },
  "6795": { office: "Office of Energy & Transportation", industryTitle: "MINERAL ROYALTY TRADERS" },
  "6798": { office: "Office of Real Estate & Construction", industryTitle: "REAL ESTATE INVESTMENT TRUSTS" },
  "6799": { office: "Office of Real Estate & Construction", industryTitle: "INVESTORS, NEC" },
  "7000": { office: "Office of Real Estate & Construction", industryTitle: "HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES" },
  "7011": { office: "Office of Real Estate & Construction", industryTitle: "HOTELS & MOTELS" },
  "7200": { office: "Office of Trade & Services", industryTitle: "SERVICES-PERSONAL SERVICES" },
  "7310": { office: "Office of Trade & Services", industryTitle: "SERVICES-ADVERTISING" },
  "7311": { office: "Office of Trade & Services", industryTitle: "SERVICES-ADVERTISING AGENCIES" },
  "7320": { office: "Office of Trade & Services", industryTitle: "SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES" },
  "7330": { office: "Office of Trade & Services", industryTitle: "SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY" },
  "7331": { office: "Office of Trade & Services", industryTitle: "SERVICES-DIRECT MAIL ADVERTISING SERVICES" },
  "7340": { office: "Office of Trade & Services", industryTitle: "SERVICES-TO DWELLINGS & OTHER BUILDINGS" },
  "7350": { office: "Office of Trade & Services", industryTitle: "SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING" },
  "7359": { office: "Office of Trade & Services", industryTitle: "SERVICES-EQUIPMENT RENTAL & LEASING, NEC" },
  "7361": { office: "Office of Trade & Services", industryTitle: "SERVICES-EMPLOYMENT AGENCIES" },
  "7363": { office: "Office of Trade & Services", industryTitle: "SERVICES-HELP SUPPLY SERVICES" },
  "7370": { office: "Office of Technology", industryTitle: "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC." },
  "7371": { office: "Office of Technology", industryTitle: "SERVICES-COMPUTER PROGRAMMING SERVICES" },
  "7372": { office: "Office of Technology", industryTitle: "SERVICES-PREPACKAGED SOFTWARE" },
  "7373": { office: "Office of Technology", industryTitle: "SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN" },
  "7374": { office: "Office of Technology", industryTitle: "SERVICES-COMPUTER PROCESSING & DATA PREPARATION" },
  "7377": { office: "Office of Trade & Services", industryTitle: "SERVICES-COMPUTER RENTAL & LEASING" },
  "7380": { office: "Office of Trade & Services", industryTitle: "SERVICES-MISCELLANEOUS BUSINESS SERVICES" },
  "7381": { office: "Office of Trade & Services", industryTitle: "SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES" },
  "7384": { office: "Office of Trade & Services", industryTitle: "SERVICES-PHOTOFINISHING LABORATORIES" },
  "7385": { office: "Office of Trade & Services", industryTitle: "SERVICES-TELEPHONE INTERCONNECT SYSTEMS" },
  "7389": { office: "Office of Trade & Services or Office of Energy & Transportation", industryTitle: "SERVICES-BUSINESS SERVICES, NEC" },
  "7500": { office: "Office of Trade & Services", industryTitle: "SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING" },
  "7510": { office: "Office of Trade & Services", industryTitle: "SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)" },
  "7600": { office: "Office of Trade & Services", industryTitle: "SERVICES-MISCELLANEOUS REPAIR SERVICES" },
  "7812": { office: "Office of Trade & Services", industryTitle: "SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION" },
  "7819": { office: "Office of Trade & Services", industryTitle: "SERVICES-ALLIED TO MOTION PICTURE PRODUCTION" },
  "7822": { office: "Office of Trade & Services", industryTitle: "SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION" },
  "7829": { office: "Office of Trade & Services", industryTitle: "SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION" },
  "7830": { office: "Office of Trade & Services", industryTitle: "SERVICES-MOTION PICTURE THEATERS" },
  "7841": { office: "Office of Trade & Services", industryTitle: "SERVICES-VIDEO TAPE RENTAL" },
  "7900": { office: "Office of Trade & Services", industryTitle: "SERVICES-AMUSEMENT & RECREATION SERVICES" },
  "7948": { office: "Office of Trade & Services", industryTitle: "SERVICES-RACING, INCLUDING TRACK OPERATION" },
  "7990": { office: "Office of Trade & Services", industryTitle: "SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION" },
  "7997": { office: "Office of Trade & Services", industryTitle: "SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS" },
  "8000": { office: "Industrial Applications and Services", industryTitle: "SERVICES-HEALTH SERVICES" },
  "8011": { office: "Industrial Applications and Services", industryTitle: "SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE" },
  "8050": { office: "Industrial Applications and Services", industryTitle: "SERVICES-NURSING & PERSONAL CARE FACILITIES" },
  "8051": { office: "Industrial Applications and Services", industryTitle: "SERVICES-SKILLED NURSING CARE FACILITIES" },
  "8060": { office: "Industrial Applications and Services", industryTitle: "SERVICES-HOSPITALS" },
  "8062": { office: "Industrial Applications and Services", industryTitle: "SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC" },
  "8071": { office: "Industrial Applications and Services", industryTitle: "SERVICES-MEDICAL LABORATORIES" },
  "8082": { office: "Industrial Applications and Services", industryTitle: "SERVICES-HOME HEALTH CARE SERVICES" },
  "8090": { office: "Industrial Applications and Services", industryTitle: "SERVICES-MISC HEALTH & ALLIED SERVICES, NEC" },
  "8093": { office: "Industrial Applications and Services", industryTitle: "SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC" },
  "8111": { office: "Office of Trade & Services", industryTitle: "SERVICES-LEGAL SERVICES" },
  "8200": { office: "Office of Trade & Services", industryTitle: "SERVICES-EDUCATIONAL SERVICES" },
  "8300": { office: "Industrial Applications and Services", industryTitle: "SERVICES-SOCIAL SERVICES" },
  "8351": { office: "Office of Trade & Services", industryTitle: "SERVICES-CHILD DAY CARE SERVICES" },
  "8600": { office: "Office of Trade & Services", industryTitle: "SERVICES-MEMBERSHIP ORGANIZATIONS" },
  "8700": { office: "Office of Trade & Services", industryTitle: "SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT" },
  "8711": { office: "Office of Trade & Services", industryTitle: "SERVICES-ENGINEERING SERVICES" },
  "8731": { office: "Industrial Applications and Services", industryTitle: "SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH" },
  "8734": { office: "Industrial Applications and Services", industryTitle: "SERVICES-TESTING LABORATORIES" },
  "8741": { office: "Office of Trade & Services", industryTitle: "SERVICES-MANAGEMENT SERVICES" },
  "8742": { office: "Office of Trade & Services", industryTitle: "SERVICES-MANAGEMENT CONSULTING SERVICES" },
  "8744": { office: "Office of Trade & Services", industryTitle: "SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES" },
  "8880": { office: "Office of International Corp Fin", industryTitle: "AMERICAN DEPOSITARY RECEIPTS" },
  "8888": { office: "Office of International Corp Fin", industryTitle: "FOREIGN GOVERNMENTS" },
  "8900": { office: "Office of Trade & Services", industryTitle: "SERVICES-SERVICES, NEC" },
  "9721": { office: "Office of International Corp Fin", industryTitle: "INTERNATIONAL AFFAIRS" },
  "9995": { office: "Office of Real Estate & Construction", industryTitle: "NON-OPERATING ESTABLISHMENTS" },
} as const satisfies Record<string, SICCodeMetadata>;

/**
 * Backward-compatible map of SIC code to industry description.
 */
export const SIC_CODES = {
  "100": "AGRICULTURAL PRODUCTION-CROPS",
  "200": "AGRICULTURAL PROD-LIVESTOCK & ANIMAL SPECIALTIES",
  "700": "AGRICULTURAL SERVICES",
  "800": "FORESTRY",
  "900": "FISHING, HUNTING AND TRAPPING",
  "1000": "METAL MINING",
  "1040": "GOLD AND SILVER ORES",
  "1090": "MISCELLANEOUS METAL ORES",
  "1220": "BITUMINOUS COAL & LIGNITE MINING",
  "1221": "BITUMINOUS COAL & LIGNITE SURFACE MINING",
  "1311": "CRUDE PETROLEUM & NATURAL GAS",
  "1381": "DRILLING OIL & GAS WELLS",
  "1382": "OIL & GAS FIELD EXPLORATION SERVICES",
  "1389": "OIL & GAS FIELD SERVICES, NEC",
  "1400": "MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)",
  "1520": "GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS",
  "1531": "OPERATIVE BUILDERS",
  "1540": "GENERAL BLDG CONTRACTORS - NONRESIDENTIAL BLDGS",
  "1600": "HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS",
  "1623": "WATER, SEWER, PIPELINE, COMM & POWER LINE CONSTRUCTION",
  "1700": "CONSTRUCTION - SPECIAL TRADE CONTRACTORS",
  "1731": "ELECTRICAL WORK",
  "2000": "FOOD AND KINDRED PRODUCTS",
  "2011": "MEAT PACKING PLANTS",
  "2013": "SAUSAGES & OTHER PREPARED MEAT PRODUCTS",
  "2015": "POULTRY SLAUGHTERING AND PROCESSING",
  "2020": "DAIRY PRODUCTS",
  "2024": "ICE CREAM & FROZEN DESSERTS",
  "2030": "CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES",
  "2033": "CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES",
  "2040": "GRAIN MILL PRODUCTS",
  "2050": "BAKERY PRODUCTS",
  "2052": "COOKIES & CRACKERS",
  "2060": "SUGAR & CONFECTIONERY PRODUCTS",
  "2070": "FATS & OILS",
  "2080": "BEVERAGES",
  "2082": "MALT BEVERAGES",
  "2086": "BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS",
  "2090": "MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS",
  "2092": "PREPARED FRESH OR FROZEN FISH & SEAFOODS",
  "2100": "TOBACCO PRODUCTS",
  "2111": "CIGARETTES",
  "2200": "TEXTILE MILL PRODUCTS",
  "2211": "BROADWOVEN FABRIC MILLS, COTTON",
  "2221": "BROADWOVEN FABRIC MILLS, MAN MADE FIBER & SILK",
  "2250": "KNITTING MILLS",
  "2253": "KNIT OUTERWEAR MILLS",
  "2273": "CARPETS & RUGS",
  "2300": "APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL",
  "2320": "MEN'S & BOYS' FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS",
  "2330": "WOMEN'S, MISSES', AND JUNIORS OUTERWEAR",
  "2340": "WOMEN'S, MISSES', CHILDREN'S & INFANTS' UNDERGARMENTS",
  "2390": "MISCELLANEOUS FABRICATED TEXTILE PRODUCTS",
  "2400": "LUMBER & WOOD PRODUCTS (NO FURNITURE)",
  "2421": "SAWMILLS & PLANTING MILLS, GENERAL",
  "2430": "MILLWOOD, VENEER, PLYWOOD, & STRUCTURAL WOOD MEMBERS",
  "2451": "MOBILE HOMES",
  "2452": "PREFABRICATED WOOD BLDGS & COMPONENTS",
  "2510": "HOUSEHOLD FURNITURE",
  "2511": "WOOD HOUSEHOLD FURNITURE, (NO UPHOLSTERED)",
  "2520": "OFFICE FURNITURE",
  "2522": "OFFICE FURNITURE (NO WOOD)",
  "2531": "PUBLIC BLDG & RELATED FURNITURE",
  "2540": "PARTITIONS, SHELVG, LOCKERS, & OFFICE & STORE FIXTURES",
  "2590": "MISCELLANEOUS FURNITURE & FIXTURES",
  "2600": "PAPERS & ALLIED PRODUCTS",
  "2611": "PULP MILLS",
  "2621": "PAPER MILLS",
  "2631": "PAPERBOARD MILLS",
  "2650": "PAPERBOARD CONTAINERS & BOXES",
  "2670": "CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)",
  "2673": "PLASTICS, FOIL & COATED PAPER BAGS",
  "2711": "NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING",
  "2721": "PERIODICALS: PUBLISHING OR PUBLISHING & PRINTING",
  "2731": "BOOKS: PUBLISHING OR PUBLISHING & PRINTING",
  "2732": "BOOK PRINTING",
  "2741": "MISCELLANEOUS PUBLISHING",
  "2750": "COMMERCIAL PRINTING",
  "2761": "MANIFOLD BUSINESS FORMS",
  "2771": "GREETING CARDS",
  "2780": "BLANKBOOKS, LOOSELEAF BINDERS & BOOKBINDG & RELATD WORK",
  "2790": "SERVICE INDUSTRIES FOR THE PRINTING TRADE",
  "2800": "CHEMICALS & ALLIED PRODUCTS",
  "2810": "INDUSTRIAL INORGANIC CHEMICALS",
  "2820": "PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)",
  "2821": "PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS",
  "2833": "MEDICINAL CHEMICALS & BOTANICAL PRODUCTS",
  "2834": "PHARMACEUTICAL PREPARATIONS",
  "2835": "IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES",
  "2836": "BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)",
  "2840": "SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS",
  "2842": "SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS",
  "2844": "PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS",
  "2851": "PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS",
  "2860": "INDUSTRIAL ORGANIC CHEMICALS",
  "2870": "AGRICULTURAL CHEMICALS",
  "2890": "MISCELLANEOUS CHEMICAL PRODUCTS",
  "2891": "ADHESIVES & SEALANTS",
  "2911": "PETROLEUM REFINING",
  "2950": "ASPHALT PAVING & ROOFING MATERIALS",
  "2990": "MISCELLANEOUS PRODUCTS OF PETROLEUM & COAL",
  "3011": "TIRES & INNER TUBES",
  "3021": "RUBBER & PLASTICS FOOTWEAR",
  "3050": "GASKETS, PACKG & SEALG DEVICES & RUBBER & PLASTICS HOSE",
  "3060": "FABRICATED RUBBER PRODUCTS, NEC",
  "3080": "MISCELLANEOUS PLASTICS PRODUCTS",
  "3081": "UNSUPPORTED PLASTICS FILM & SHEET",
  "3086": "PLASTICS FOAM PRODUCTS",
  "3089": "PLASTICS PRODUCTS, NEC",
  "3100": "LEATHER & LEATHER PRODUCTS",
  "3140": "FOOTWEAR, (NO RUBBER)",
  "3211": "FLAT GLASS",
  "3220": "GLASS & GLASSWARE, PRESSED OR BLOWN",
  "3221": "GLASS CONTAINERS",
  "3231": "GLASS PRODUCTS, MADE OF PURCHASED GLASS",
  "3241": "CEMENT, HYDRAULIC",
  "3250": "STRUCTURAL CLAY PRODUCTS",
  "3260": "POTTERY & RELATED PRODUCTS",
  "3270": "CONCRETE, GYPSUM & PLASTER PRODUCTS",
  "3272": "CONCRETE PRODUCTS, EXCEPT BLOCK & BRICK",
  "3281": "CUT STONE & STONE PRODUCTS",
  "3290": "ABRASIVE, ASBESTOS & MISC NONMETALLIC MINERAL PRODS",
  "3310": "STEEL WORKS, BLAST FURNACES & ROLLING & FINISHING MILLS",
  "3312": "STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)",
  "3317": "STEEL PIPE & TUBES",
  "3320": "IRON & STEEL FOUNDRIES",
  "3330": "PRIMARY SMELTING & REFINING OF NONFERROUS METALS",
  "3334": "PRIMARY PRODUCTION OF ALUMINUM",
  "3341": "SECONDARY SMELTING & REFINING OF NONFERROUS METALS",
  "3350": "ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS",
  "3357": "DRAWING & INSULATING OF NONFERROUS WIRE",
  "3360": "NONFERROUS FOUNDRIES (CASTINGS)",
  "3390": "MISCELLANEOUS PRIMARY METAL PRODUCTS",
  "3411": "METAL CANS",
  "3412": "METAL SHIPPING BARRELS, DRUMS, KEGS & PAILS",
  "3420": "CUTLERY, HANDTOOLS & GENERAL HARDWARE",
  "3430": "HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES",
  "3433": "HEATING EQUIPMENT, EXCEPT ELECTRIC & WARM AIR FURNACES",
  "3440": "FABRICATED STRUCTURAL METAL PRODUCTS",
  "3442": "METAL DOORS, SASH, FRAMES, MOLDINGS & TRIM",
  "3443": "FABRICATED PLATE WORK (BOILER SHOPS)",
  "3444": "SHEET METAL WORK",
  "3448": "PREFABRICATED METAL BUILDINGS & COMPONENTS",
  "3451": "SCREW MACHINE PRODUCTS",
  "3452": "BOLTS, NUTS, SCREWS, RIVETS & WASHERS",
  "3460": "METAL FORGINGS & STAMPINGS",
  "3470": "COATING, ENGRAVING & ALLIED SERVICES",
  "3480": "ORDNANCE & ACCESSORIES, (NO VEHICLES/GUIDED MISSILES)",
  "3490": "MISCELLANEOUS FABRICATED METAL PRODUCTS",
  "3510": "ENGINES & TURBINES",
  "3523": "FARM MACHINERY & EQUIPMENT",
  "3524": "LAWN & GARDEN TRACTORS & HOME LAWN & GARDENS EQUIP",
  "3530": "CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP",
  "3531": "CONSTRUCTION MACHINERY & EQUIP",
  "3532": "MINING MACHINERY & EQUIP (NO OIL & GAS FIELD MACH & EQUIP)",
  "3533": "OIL & GAS FIELD MACHINERY & EQUIPMENT",
  "3537": "INDUSTRIAL TRUCKS, TRACTORS, TRAILORS & STACKERS",
  "3540": "METALWORKG MACHINERY & EQUIPMENT",
  "3541": "MACHINE TOOLS, METAL CUTTING TYPES",
  "3550": "SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)",
  "3555": "PRINTING TRADES MACHINERY & EQUIPMENT",
  "3559": "SPECIAL INDUSTRY MACHINERY, NEC",
  "3560": "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT",
  "3561": "PUMPS & PUMPING EQUIPMENT",
  "3562": "BALL & ROLLER BEARINGS",
  "3564": "INDUSTRIAL & COMMERCIAL FANS & BLOWERS & AIR PURIFING EQUIP",
  "3567": "INDUSTRIAL PROCESS FURNACES & OVENS",
  "3569": "GENERAL INDUSTRIAL MACHINERY & EQUIPMENT, NEC",
  "3570": "COMPUTER & OFFICE EQUIPMENT",
  "3571": "ELECTRONIC COMPUTERS",
  "3572": "COMPUTER STORAGE DEVICES",
  "3575": "COMPUTER TERMINALS",
  "3576": "COMPUTER COMMUNICATIONS EQUIPMENT",
  "3577": "COMPUTER PERIPHERAL EQUIPMENT, NEC",
  "3578": "CALCULATING & ACCOUNTING MACHINES (NO ELECTRONIC COMPUTERS)",
  "3579": "OFFICE MACHINES, NEC",
  "3580": "REFRIGERATION & SERVICE INDUSTRY MACHINERY",
  "3585": "AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP",
  "3590": "MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT",
  "3600": "ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)",
  "3612": "POWER, DISTRIBUTION & SPECIALTY TRANSFORMERS",
  "3613": "SWITCHGEAR & SWITCHBOARD APPARATUS",
  "3620": "ELECTRICAL INDUSTRIAL APPARATUS",
  "3621": "MOTORS & GENERATORS",
  "3630": "HOUSEHOLD APPLIANCES",
  "3634": "ELECTRIC HOUSEWARES & FANS",
  "3640": "ELECTRIC LIGHTING & WIRING EQUIPMENT",
  "3651": "HOUSEHOLD AUDIO & VIDEO EQUIPMENT",
  "3652": "PHONOGRAPH RECORDS & PRERECORDED AUDIO TAPES & DISKS",
  "3661": "TELEPHONE & TELEGRAPH APPARATUS",
  "3663": "RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT",
  "3669": "COMMUNICATIONS EQUIPMENT, NEC",
  "3670": "ELECTRONIC COMPONENTS & ACCESSORIES",
  "3672": "PRINTED CIRCUIT BOARDS",
  "3674": "SEMICONDUCTORS & RELATED DEVICES",
  "3677": "ELECTRONIC COILS, TRANSFORMERS & OTHER INDUCTORS",
  "3678": "ELECTRONIC CONNECTORS",
  "3679": "ELECTRONIC COMPONENTS, NEC",
  "3690": "MISCELLANEOUS ELECTRICAL MACHINERY, EQUIPMENT & SUPPLIES",
  "3695": "MAGNETIC & OPTICAL RECORDING MEDIA",
  "3711": "MOTOR VEHICLES & PASSENGER CAR BODIES",
  "3713": "TRUCK & BUS BODIES",
  "3714": "MOTOR VEHICLE PARTS & ACCESSORIES",
  "3715": "TRUCK TRAILERS",
  "3716": "MOTOR HOMES",
  "3720": "AIRCRAFT & PARTS",
  "3721": "AIRCRAFT",
  "3724": "AIRCRAFT ENGINES & ENGINE PARTS",
  "3728": "AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC",
  "3730": "SHIP & BOAT BUILDING & REPAIRING",
  "3743": "RAILROAD EQUIPMENT",
  "3751": "MOTORCYCLES, BICYCLES & PARTS",
  "3760": "GUIDED MISSILES & SPACE VEHICLES & PARTS",
  "3790": "MISCELLANEOUS TRANSPORTATION EQUIPMENT",
  "3812": "SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS",
  "3821": "LABORATORY APPARATUS & FURNITURE",
  "3822": "AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS",
  "3823": "INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL",
  "3824": "TOTALIZING FLUID METERS & COUNTING DEVICES",
  "3825": "INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS",
  "3826": "LABORATORY ANALYTICAL INSTRUMENTS",
  "3827": "OPTICAL INSTRUMENTS & LENSES",
  "3829": "MEASURING & CONTROLLING DEVICES, NEC",
  "3841": "SURGICAL & MEDICAL INSTRUMENTS & APPARATUS",
  "3842": "ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES",
  "3843": "DENTAL EQUIPMENT & SUPPLIES",
  "3844": "X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS",
  "3845": "ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS",
  "3851": "OPHTHALMIC GOODS",
  "3861": "PHOTOGRAPHIC EQUIPMENT & SUPPLIES",
  "3873": "WATCHES, CLOCKS, CLOCKWORK OPERATED DEVICES/PARTS",
  "3910": "JEWELRY, SILVERWARE & PLATED WARE",
  "3911": "JEWELRY, PRECIOUS METAL",
  "3931": "MUSICAL INSTRUMENTS",
  "3942": "DOLLS & STUFFED TOYS",
  "3944": "GAMES, TOYS & CHILDREN'S VEHICLES (NO DOLLS & BICYCLES)",
  "3949": "SPORTING & ATHLETIC GOODS, NEC",
  "3950": "PENS, PENCILS & OTHER ARTISTS' MATERIALS",
  "3960": "COSTUME JEWELRY & NOVELTIES",
  "3990": "MISCELLANEOUS MANUFACTURING INDUSTRIES",
  "4011": "RAILROADS, LINE-HAUL OPERATING",
  "4013": "RAILROAD SWITCHING & TERMINAL ESTABLISHMENTS",
  "4100": "LOCAL & SUBURBAN TRANSIT & INTERURBAN HWY PASSENGER TRANS",
  "4210": "TRUCKING & COURIER SERVICES (NO AIR)",
  "4213": "TRUCKING (NO LOCAL)",
  "4220": "PUBLIC WAREHOUSING & STORAGE",
  "4231": "TERMINAL MAINTENANCE FACILITIES FOR MOTOR FREIGHT TRANSPORT",
  "4400": "WATER TRANSPORTATION",
  "4412": "DEEP SEA FOREIGN TRANSPORTATION OF FREIGHT",
  "4512": "AIR TRANSPORTATION, SCHEDULED",
  "4513": "AIR COURIER SERVICES",
  "4522": "AIR TRANSPORTATION, NONSCHEDULED",
  "4581": "AIRPORTS, FLYING FIELDS & AIRPORT TERMINAL SERVICES",
  "4610": "PIPE LINES (NO NATURAL GAS)",
  "4700": "TRANSPORTATION SERVICES",
  "4731": "ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO",
  "4812": "RADIOTELEPHONE COMMUNICATIONS",
  "4813": "TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)",
  "4822": "TELEGRAPH & OTHER MESSAGE COMMUNICATIONS",
  "4832": "RADIO BROADCASTING STATIONS",
  "4833": "TELEVISION BROADCASTING STATIONS",
  "4841": "CABLE & OTHER PAY TELEVISION SERVICES",
  "4899": "COMMUNICATIONS SERVICES, NEC",
  "4900": "ELECTRIC, GAS & SANITARY SERVICES",
  "4911": "ELECTRIC SERVICES",
  "4922": "NATURAL GAS TRANSMISSION",
  "4923": "NATURAL GAS TRANSMISISON & DISTRIBUTION",
  "4924": "NATURAL GAS DISTRIBUTION",
  "4931": "ELECTRIC & OTHER SERVICES COMBINED",
  "4932": "GAS & OTHER SERVICES COMBINED",
  "4941": "WATER SUPPLY",
  "4950": "SANITARY SERVICES",
  "4953": "REFUSE SYSTEMS",
  "4955": "HAZARDOUS WASTE MANAGEMENT",
  "4961": "STEAM & AIR-CONDITIONING SUPPLY",
  "4991": "COGENERATION SERVICES & SMALL POWER PRODUCERS",
  "5000": "WHOLESALE-DURABLE GOODS",
  "5010": "WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES",
  "5013": "WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS",
  "5020": "WHOLESALE-FURNITURE & HOME FURNISHINGS",
  "5030": "WHOLESALE-LUMBER & OTHER CONSTRUCTION MATERIALS",
  "5031": "WHOLESALE-LUMBER, PLYWOOD, MILLWORK & WOOD PANELS",
  "5040": "WHOLESALE-PROFESSIONAL & COMMERCIAL EQUIPMENT & SUPPLIES",
  "5045": "WHOLESALE-COMPUTERS & PERIPHERAL EQUIPMENT & SOFTWARE",
  "5047": "WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES",
  "5050": "WHOLESALE-METALS & MINERALS (NO PETROLEUM)",
  "5051": "WHOLESALE-METALS SERVICE CENTERS & OFFICES",
  "5063": "WHOLESALE-ELECTRICAL APPARATUS & EQUIPMENT, WIRING SUPPLIES",
  "5064": "WHOLESALE-ELECTRICAL APPLIANCES, TV & RADIO SETS",
  "5065": "WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC",
  "5070": "WHOLESALE-HARDWARE & PLUMBING & HEATING EQUIPMENT & SUPPLIES",
  "5072": "WHOLESALE-HARDWARE",
  "5080": "WHOLESALE-MACHINERY, EQUIPMENT & SUPPLIES",
  "5082": "WHOLESALE-CONSTRUCTION & MINING (NO PETRO) MACHINERY & EQUIP",
  "5084": "WHOLESALE-INDUSTRIAL MACHINERY & EQUIPMENT",
  "5090": "WHOLESALE-MISC DURABLE GOODS",
  "5094": "WHOLESALE-JEWELRY, WATCHES, PRECIOUS STONES & METALS",
  "5099": "WHOLESALE-DURABLE GOODS, NEC",
  "5110": "WHOLESALE-PAPER & PAPER PRODUCTS",
  "5122": "WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS' SUNDRIES",
  "5130": "WHOLESALE-APPAREL, PIECE GOODS & NOTIONS",
  "5140": "WHOLESALE-GROCERIES & RELATED PRODUCTS",
  "5141": "WHOLESALE-GROCERIES, GENERAL LINE",
  "5150": "WHOLESALE-FARM PRODUCT RAW MATERIALS",
  "5160": "WHOLESALE-CHEMICALS & ALLIED PRODUCTS",
  "5171": "WHOLESALE-PETROLEUM BULK STATIONS & TERMINALS",
  "5172": "WHOLESALE-PETROLEUM & PETROLEUM PRODUCTS (NO BULK STATIONS)",
  "5180": "WHOLESALE-BEER, WINE & DISTILLED ALCOHOLIC BEVERAGES",
  "5190": "WHOLESALE-MISCELLANEOUS NONDURABLE GOODS",
  "5200": "RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY",
  "5211": "RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS",
  "5271": "RETAIL-MOBILE HOME DEALERS",
  "5311": "RETAIL-DEPARTMENT STORES",
  "5331": "RETAIL-VARIETY STORES",
  "5399": "RETAIL-MISC GENERAL MERCHANDISE STORES",
  "5400": "RETAIL-FOOD STORES",
  "5411": "RETAIL-GROCERY STORES",
  "5412": "RETAIL-CONVENIENCE STORES",
  "5500": "RETAIL-AUTO DEALERS & GASOLINE STATIONS",
  "5531": "RETAIL-AUTO & HOME SUPPLY STORES",
  "5600": "RETAIL-APPAREL & ACCESSORY STORES",
  "5621": "RETAIL-WOMEN'S CLOTHING STORES",
  "5651": "RETAIL-FAMILY CLOTHING STORES",
  "5661": "RETAIL-SHOE STORES",
  "5700": "RETAIL-HOME FURNITURE, FURNISHINGS & EQUIPMENT STORES",
  "5712": "RETAIL-FURNITURE STORES",
  "5731": "RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES",
  "5734": "RETAIL-COMPUTER & COMPUTER SOFTWARE STORES",
  "5735": "RETAIL-RECORD & PRERECORDED TAPE STORES",
  "5810": "RETAIL-EATING & DRINKING PLACES",
  "5812": "RETAIL-EATING PLACES",
  "5900": "RETAIL-MISCELLANEOUS RETAIL",
  "5912": "RETAIL-DRUG STORES AND PROPRIETARY STORES",
  "5940": "RETAIL-MISCELLANEOUS SHOPPING GOODS STORES",
  "5944": "RETAIL-JEWELRY STORES",
  "5945": "RETAIL-HOBBY, TOY & GAME SHOPS",
  "5960": "RETAIL-NONSTORE RETAILERS",
  "5961": "RETAIL-CATALOG & MAIL-ORDER HOUSES",
  "5990": "RETAIL-RETAIL STORES, NEC",
  "6021": "NATIONAL COMMERCIAL BANKS",
  "6022": "STATE COMMERCIAL BANKS",
  "6029": "COMMERCIAL BANKS, NEC",
  "6035": "SAVINGS INSTITUTION, FEDERALLY CHARTERED",
  "6036": "SAVINGS INSTITUTIONS, NOT FEDERALLY CHARTERED",
  "6099": "FUNCTIONS RELATED TO DEPOSITORY BANKING, NEC",
  "6111": "FEDERAL & FEDERALLY-SPONSORED CREDIT AGENCIES",
  "6141": "PERSONAL CREDIT INSTITUTIONS",
  "6153": "SHORT-TERM BUSINESS CREDIT INSTITUTIONS",
  "6159": "MISCELLANEOUS BUSINESS CREDIT INSTITUTION",
  "6162": "MORTGAGE BANKERS & LOAN CORRESPONDENTS",
  "6163": "LOAN BROKERS",
  "6172": "FINANCE LESSORS",
  "6189": "ASSET-BACKED SECURITIES",
  "6199": "FINANCE SERVICES",
  "6200": "SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES",
  "6211": "SECURITY BROKERS, DEALERS & FLOTATION COMPANIES",
  "6221": "COMMODITY CONTRACTS BROKERS & DEALERS",
  "6282": "INVESTMENT ADVICE",
  "6311": "LIFE INSURANCE",
  "6321": "ACCIDENT & HEALTH INSURANCE",
  "6324": "HOSPITAL & MEDICAL SERVICE PLANS",
  "6331": "FIRE, MARINE & CASUALTY INSURANCE",
  "6351": "SURETY INSURANCE",
  "6361": "TITLE INSURANCE",
  "6399": "INSURANCE CARRIERS, NEC",
  "6411": "INSURANCE AGENTS, BROKERS & SERVICE",
  "6500": "REAL ESTATE",
  "6510": "REAL ESTATE OPERATORS (NO DEVELOPERS) & LESSORS",
  "6512": "OPERATORS OF NONRESIDENTIAL BUILDINGS",
  "6513": "OPERATORS OF APARTMENT BUILDINGS",
  "6519": "LESSORS OF REAL PROPERTY, NEC",
  "6531": "REAL ESTATE AGENTS & MANAGERS (FOR OTHERS)",
  "6532": "REAL ESTATE DEALERS (FOR THEIR OWN ACCOUNT)",
  "6552": "LAND SUBDIVIDERS & DEVELOPERS (NO CEMETERIES)",
  "6770": "BLANK CHECKS",
  "6792": "OIL ROYALTY TRADERS",
  "6794": "PATENT OWNERS & LESSORS",
  "6795": "MINERAL ROYALTY TRADERS",
  "6798": "REAL ESTATE INVESTMENT TRUSTS",
  "6799": "INVESTORS, NEC",
  "7000": "HOTELS, ROOMING HOUSES, CAMPS & OTHER LODGING PLACES",
  "7011": "HOTELS & MOTELS",
  "7200": "SERVICES-PERSONAL SERVICES",
  "7310": "SERVICES-ADVERTISING",
  "7311": "SERVICES-ADVERTISING AGENCIES",
  "7320": "SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES",
  "7330": "SERVICES-MAILING, REPRODUCTION, COMMERCIAL ART & PHOTOGRAPHY",
  "7331": "SERVICES-DIRECT MAIL ADVERTISING SERVICES",
  "7340": "SERVICES-TO DWELLINGS & OTHER BUILDINGS",
  "7350": "SERVICES-MISCELLANEOUS EQUIPMENT RENTAL & LEASING",
  "7359": "SERVICES-EQUIPMENT RENTAL & LEASING, NEC",
  "7361": "SERVICES-EMPLOYMENT AGENCIES",
  "7363": "SERVICES-HELP SUPPLY SERVICES",
  "7370": "SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.",
  "7371": "SERVICES-COMPUTER PROGRAMMING SERVICES",
  "7372": "SERVICES-PREPACKAGED SOFTWARE",
  "7373": "SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN",
  "7374": "SERVICES-COMPUTER PROCESSING & DATA PREPARATION",
  "7377": "SERVICES-COMPUTER RENTAL & LEASING",
  "7380": "SERVICES-MISCELLANEOUS BUSINESS SERVICES",
  "7381": "SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES",
  "7384": "SERVICES-PHOTOFINISHING LABORATORIES",
  "7385": "SERVICES-TELEPHONE INTERCONNECT SYSTEMS",
  "7389": "SERVICES-BUSINESS SERVICES, NEC",
  "7500": "SERVICES-AUTOMOTIVE REPAIR, SERVICES & PARKING",
  "7510": "SERVICES-AUTO RENTAL & LEASING (NO DRIVERS)",
  "7600": "SERVICES-MISCELLANEOUS REPAIR SERVICES",
  "7812": "SERVICES-MOTION PICTURE & VIDEO TAPE PRODUCTION",
  "7819": "SERVICES-ALLIED TO MOTION PICTURE PRODUCTION",
  "7822": "SERVICES-MOTION PICTURE & VIDEO TAPE DISTRIBUTION",
  "7829": "SERVICES-ALLIED TO MOTION PICTURE DISTRIBUTION",
  "7830": "SERVICES-MOTION PICTURE THEATERS",
  "7841": "SERVICES-VIDEO TAPE RENTAL",
  "7900": "SERVICES-AMUSEMENT & RECREATION SERVICES",
  "7948": "SERVICES-RACING, INCLUDING TRACK OPERATION",
  "7990": "SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION",
  "7997": "SERVICES-MEMBERSHIP SPORTS & RECREATION CLUBS",
  "8000": "SERVICES-HEALTH SERVICES",
  "8011": "SERVICES-OFFICES & CLINICS OF DOCTORS OF MEDICINE",
  "8050": "SERVICES-NURSING & PERSONAL CARE FACILITIES",
  "8051": "SERVICES-SKILLED NURSING CARE FACILITIES",
  "8060": "SERVICES-HOSPITALS",
  "8062": "SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC",
  "8071": "SERVICES-MEDICAL LABORATORIES",
  "8082": "SERVICES-HOME HEALTH CARE SERVICES",
  "8090": "SERVICES-MISC HEALTH & ALLIED SERVICES, NEC",
  "8093": "SERVICES-SPECIALTY OUTPATIENT FACILITIES, NEC",
  "8111": "SERVICES-LEGAL SERVICES",
  "8200": "SERVICES-EDUCATIONAL SERVICES",
  "8300": "SERVICES-SOCIAL SERVICES",
  "8351": "SERVICES-CHILD DAY CARE SERVICES",
  "8600": "SERVICES-MEMBERSHIP ORGANIZATIONS",
  "8700": "SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT",
  "8711": "SERVICES-ENGINEERING SERVICES",
  "8731": "SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH",
  "8734": "SERVICES-TESTING LABORATORIES",
  "8741": "SERVICES-MANAGEMENT SERVICES",
  "8742": "SERVICES-MANAGEMENT CONSULTING SERVICES",
  "8744": "SERVICES-FACILITIES SUPPORT MANAGEMENT SERVICES",
  "8880": "AMERICAN DEPOSITARY RECEIPTS",
  "8888": "FOREIGN GOVERNMENTS",
  "8900": "SERVICES-SERVICES, NEC",
  "9721": "INTERNATIONAL AFFAIRS",
  "9995": "NON-OPERATING ESTABLISHMENTS",
} as const;

/**
 * Type for valid SIC codes.
 */
export type SICCode = keyof typeof SIC_CODE_METADATA;

/**
 * Normalize SIC code input for lookups.
 * Accepts both canonical SEC codes (e.g. "100") and zero-padded forms (e.g. "0100").
 */
export function normalizeSICCode(
  code: string | undefined | null,
): SICCode | undefined {
  if (!code) return undefined;

  const trimmed = code.trim();
  if (trimmed in SIC_CODE_METADATA) {
    return trimmed as SICCode;
  }

  if (/^\d+$/.test(trimmed)) {
    const unpadded = String(Number(trimmed));
    if (unpadded in SIC_CODE_METADATA) {
      return unpadded as SICCode;
    }
  }

  return undefined;
}

/**
 * Get SIC metadata (office + industry title).
 */
export function getSICMetadata(
  code: string | undefined | null,
): SICCodeMetadata | undefined {
  const normalized = normalizeSICCode(code);
  if (!normalized) return undefined;
  return SIC_CODE_METADATA[normalized];
}

/**
 * Get SIC code description (industry title).
 */
export function getSICDescription(
  code: string | undefined | null,
): string | undefined {
  const metadata = getSICMetadata(code);
  return metadata?.industryTitle;
}

/**
 * Get SEC office for an SIC code.
 */
export function getSICOffice(
  code: string | undefined | null,
): string | undefined {
  const metadata = getSICMetadata(code);
  return metadata?.office;
}
